### ISSUE TITLE
Server stopping when Connection lost with Redis

### ISSUE THREAD

**Issue by MatheusPortoRupee** [redis/redis-rb#1029]
- Versions:

ActionCable 5.2.4.3
Redis 4.4.0
Ruby 2.4.0
Rails 5.2.4.3

- Scenario:

The Redis server is on an external machine, and I'm using Action Cable.

ActionCable with Redis works perfectly, the problem is that when the connection with the Redis server is somehow lost, it ends up stopping the Rails server. I would like him to keep trying to connect me until the connection is re-established.

My cable.yml:

![image](https://user-images.githubusercontent.com/63735608/133332422-99e10731-7bb4-4a24-a0bd-d38fab7d9299.png)

**Starting the server without connecting to Redis**

When keeping the Redis server offline, and trying to start the Rails server, it will try to connect to Redis and it will stop the Rails server

![image](https://user-images.githubusercontent.com/63735608/133330743-2ba29b9f-47e7-4981-b84a-affd19b18b57.png)

Server with connection to Redis (normally working), if at any time it loses a connection where the Redis server is present, it will shut down the server. Instead of trying to reconnect asynchronously.

![image](https://user-images.githubusercontent.com/63735608/133331040-21e98c71-cdcc-4a55-a11a-3fa1235723d5.png)

**How can I resolve this issue?**

**Comment by byroot** [comment]
Can't say, but this is very unlikely to be a redis-rb issue. The caller (Action Cable in this instance) is responsible for dealing with this kind of errors.

If you report this elsewhere make sure to include full backtraces in text form, not screenshots.

**Comment by MatheusPortoRupee** [comment]
The error is coming directly from the Redis gem

```
Exiting
/home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis/client.rb:292:in `rescue in io': Connection lost (ECONNRESET) (Redis::ConnectionError)
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis/client.rb:285:in `io'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis/client.rb:296:in `read'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis/client.rb:164:in `block (3 levels) in call_loop'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis/client.rb:163:in `loop'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis/client.rb:163:in `block (2 levels) in call_loop'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis/client.rb:265:in `block (2 levels) in process'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis/client.rb:406:in `ensure_connected'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis/client.rb:255:in `block in process'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis/client.rb:342:in `logging'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis/client.rb:254:in `process'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis/client.rb:162:in `block in call_loop'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis/client.rb:317:in `with_socket_timeout'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis/client.rb:161:in `call_loop'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis/subscribe.rb:44:in `subscription'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis/subscribe.rb:14:in `subscribe'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis.rb:3613:in `_subscription'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis.rb:2376:in `block in subscribe'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis.rb:70:in `block in synchronize'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis.rb:70:in `synchronize'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis.rb:2375:in `subscribe'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/actioncable-5.2.4.3/lib/action_cable/subscription_adapter/redis.rb:81:in `block in listen'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis/client.rb:330:in `with_reconnect'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis.rb:76:in `block in with_reconnect'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis.rb:70:in `block in synchronize'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis.rb:70:in `synchronize'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis.rb:75:in `with_reconnect'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redis-4.4.0/lib/redis.rb:82:in `without_reconnect'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/actioncable-5.2.4.3/lib/action_cable/subscription_adapter/redis.rb:78:in `listen'
        from /home/matheus/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/actioncable-5.2.4.3/lib/action_cable/subscription_adapter/redis.rb:152:in `block in ensure_listener_running'
```

**Comment by byroot** [comment]
> The error is coming directly from the Redis gem

Yes, and it's up to the caller to decide what to do with it. By default `redis-rb` tries to reconnect once, and you can up that with the `reconnect_attempts:` setting. But at some point is had to bail out.

> The images were just to exemplify the problem in a simpler way.

It's up to you, but I advise you to always to with text instead, screenshots are painful to deal with for maintainers, and so are truncated backtrace.

> I would like to know if they have any ideas to improve this aspect of reconnection?

I'm not knowledgeable about action cable, sorry.

**Comment by byroot** [comment]
Googling for: `action cable redis reconnect`

Seems like it's a long standing issue with Action Cable: https://github.com/rails/rails/issues/27659

**Comment by sergioisidoro** [comment]
I just landed here, and it seems that there's good news on the linked thread :)
https://github.com/rails/rails/issues/27659#issuecomment-1336019049
