### ISSUE TITLE
Issues  with IPv6 when url has brackets

### ISSUE THREAD

**Issue by sergioloza** [redis/redis-rb#1100]
Hello all, 

Came about a particular issue dealing with IPv6.   When initializing Redis client, it wont connect to the REDIS server if the only config parameter we send is an URL with brackets[]

Sample code that can reproduce
```
require 'redis'
require 'active_support/core_ext/hash/keys'
require 'pry'
settings = {}
settings = {
  namespace: "ddd",
  url: "redis://[valid ipv6]:6379",
  # host: "Valid",
}
r= Redis.new({:driver => :hiredis}.merge(settings.symbolize_keys))
r.connect
```

error  stack trace using hiredis  driver
```
/Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/connection/hiredis.rb:22:in `connect': nodename nor servname provided, or not known (RuntimeError)
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/connection/hiredis.rb:22:in `connect'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:371:in `establish_connection'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:117:in `block in connect'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:330:in `with_reconnect'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:116:in `connect'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:403:in `ensure_connected'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:255:in `block in process'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:342:in `logging'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:254:in `process'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:148:in `call'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis.rb:3440:in `block in method_missing'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis.rb:70:in `block in synchronize'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis.rb:70:in `synchronize'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis.rb:3439:in `method_missing'
        from redis_test.rb:12:in `<main>'
```
when the driver is Ruby (helped root causing a bit more tbh
```
/Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:384:in `rescue in establish_connection': Error connecting to Redis on [2620:118:8010:1096:250:56ff:fe83:c787]:6379 (SocketError) (Redis::CannotConnectError)
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:365:in `establish_connection'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:117:in `block in connect'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:330:in `with_reconnect'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:116:in `connect'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:403:in `ensure_connected'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:255:in `block in process'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:342:in `logging'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:254:in `process'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis/client.rb:148:in `call'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis.rb:3440:in `block in method_missing'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis.rb:70:in `block in synchronize'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis.rb:70:in `synchronize'
        from /Users/me/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/redis-4.4.0/lib/redis.rb:3439:in `method_missing'
        from redis_test.rb:12:in `<main>'
```

 Looking at the code  the URL is parsed and  resulting on host: [valid ipv6] with brackets

In the case of the ruby driver ( hiredis using a c library made it more difficult to debug), It tries to call Socket.getaddinfo
          addrinfo = ::Socket.getaddrinfo(host, nil, Socket::AF_UNSPEC, Socket::SOCK_STREAM)
Which does not like the host  having brackets and thus will fail

If you add the host as an option parameter in the initialization it works.

**Comment by sergioloza** [comment]
First time creating an issue,  i ran the client off a mac but any LINUX shows the same behavior.

**Comment by byroot** [comment]
Indeed, we'll have to add some code to handle this.

In the meantime as a workaround you can parse the URL yourself and remove the `[]` in the host, that should work.
