### ISSUE TITLE
Redis::FutureNotReady how does multi work?

### ISSUE THREAD

**Issue by gvaibhav1734** [redis/redis-rb#1109]
## How does multi and Future work?
``` ruby
self.redis.multi do |pipeline|
    @prev = pipeline.setbit(resource, 2, 1)
    pipeline.expire(resource, expiry)
end
@prev.value
```
In the above code we know that `@prev` is a `Future`.
1) Accessing `@prev.value` is safe after `redis.multi` block?
2) Do we know when exactly `@prev.value` is populated?
3) Is it asynchronous?

<details closed>

<summary>The actual issue I faced</summary>

## Issue
> Sanitized output and some parts of code. 
- The whole setup was within a rails environment where we connect to redis by passing host and port in options
```
config.redis = ConnectionPool::Wrapper.new(size: 10, timeout: 5) { Redis.new(opts) }
```
- With the script (which I ran as an rspec example) it executes `some_method` and **infrequently** results in `Redis::FutureNotReady`.
- The code was written with the assumption that after execution of `multi` block the future would be evaluated and would always have a result.

### Redis setup
- Setup redis in a docker container with limited resources. 
- Also attached a shell to it and ran `redis-cli monitor`
```
# docker-compose.yml
version: '2.3'

services:
  redis-test:
    image: redis:alpine
    mem_limit: 6m
    mem_reservation: 6m
    cpus: 0.5
    networks: 
      - host
```

### Code
``` ruby
# The ruby method (Some application code)
def some_method(resource, expiry=10)
    result = self.redis.multi do |pipeline|
	@prev = pipeline.setbit(resource, 2, 1)
	pipeline.expire(resource, expiry)
    end
    puts "*" * 64
    puts "#{Thread.current} Redis multi #{result} #{resource}"
    puts "#{Thread.current} @prev object id #{@prev.__id__}"
    # Line of interest
    puts "#{Thread.current} Redis object #{(@prev.instance_eval{@object}).to_s}"
    puts "#{Thread.current} @prev object id #{@prev.__id__}"
    # Line of interest
    puts "#{Thread.current} @prev value #{@prev.value}"
    puts "#{Thread.current} Redis timeout #{(@prev.instance_eval{@timeout}).to_s}"
    puts "#{Thread.current} Redis transformation #{(@prev.instance_eval{@transformation}).to_s}"
    puts "#{Thread.current} @prev object id #{@prev.__id__}"
    puts "#{Thread.current} @prev value #{@prev.value}"
    puts "*" * 64
end

# The script (Ran this as an example in rspec)
(1..10).each do
  threads = []
  (1..1500).each do |i|
    threads << Thread.new do
      some_method("some_key_1", 4) if i%2 == 0
      some_method("some_key_2", 4) if i%2 != 0
    end
  end
  threads.map(&:join)
end
```

### Output
- `@prev.instance_eval{@object}` evaluates to 1 but `@prev.value` raises error
- `@prev.instance_eval{@object}` evaluates to `Value will be available once the pipeline executes` but `@prev.value` evaluates to 1

The output is just weird. How do I understand it?

<details closed>

<summary>Console output</summary>

```
****************************************************************
#<Thread:0x000055fe6774b5d8 /<working_directory>/file.rb run> Redis multi [1, true] asset_processing_lock:1
#<Thread:0x000055fe6774b5d8 /<working_directory>/file.rb run> @prev object id 106040
#(Line of interest) <Thread:0x000055fe6774b5d8 /<working_directory>/file.rb run> Redis object 1 
#<Thread:0x000055fe6774b5d8 /<working_directory>/file.rb run> @prev object id 106040
#(Line of interest) <Thread:0x000055fe6774b5d8 /<working_directory>/file.rb run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        2: from /<working_directory>/file.rb:1138:in `block (6 levels) in <top (required)>'
        1: from /<working_directory>/file.rb:231 in `some_method'
/<working_directory>/vendor/cache/ruby/2.7.0/gems/redis-4.2.1/lib/redis/pipeline.rb:169:in `value': Value will be available once the pipeline executes. (Redis::FutureNotReady)
****************************************************************
#<Thread:0x000055fe679a2cf0 /<working_directory>/file.rb run> Redis multi [1, true] asset_processing_lock:2
#<Thread:0x000055fe679a2cf0 /<working_directory>/file.rb run> @prev object id 106100
#(Line of interest) <Thread:0x000055fe679a2cf0 /<working_directory>/file.rb run> Redis object Value will be available once the pipeline executes.
#<Thread:0x000055fe679a2cf0 /<working_directory>/file.rbrun> @prev object id 106100
#(Line of interest) <Thread:0x000055fe679a2cf0 /<working_directory>/file.rb run> @prev value 1
#<Thread:0x000055fe679a2cf0 /<working_directory>/file.rb run> Redis timeout 
#<Thread:0x000055fe679a2cf0 /<working_directory>/file.rb run> Redis transformation 
#<Thread:0x000055fe679a2cf0 /<working_directory>/file.rb run> @prev object id 106100
#<Thread:0x000055fe679a2cf0 /<working_directory>/file.rb run> @prev value 1
****************************************************************
```
</details>

</details>

**Comment by byroot** [comment]
> Accessing @prev.value is safe after redis.multi block?

Assuming you're not already nested in a pipeline or something, e.g.:

```ruby
@redis.pipelined do
  @redis.multi do |transaction|
     @prev = transaction.get("test")
  end
  @prev # is not ready
end
@prev # is ready

Another way a Future could not be set, is if the transaction failed, e.g.:

```ruby
begin
  @redis.multi do |transaction|
    transaction.set("test", "string")
    @prev = transaction.get("test")
    @transaction.hdel("test", "oops")
  end
rescue => error
  p error
end
@prev # is not set
```

**Comment by gvaibhav1734** [comment]
The `redis.multi` call is not wrapped with a `pipelined` block. In that case we have no way of reliably determining when the `Future` is populated?

Wrapping `multi` call with `pipelined` block is the recommended approach?

**Comment by byroot** [comment]
> Wrapping `multi` call with `pipelined` block is the recommended approach?

Absolutely not, but it sometimes happens by accident.

> In that case we have no way of reliably determining when the Future is populated?

I just explained above when they are populated: when the `EXEC` command succeed. If it doesn't succeed, then it's never populated.

**Comment by gvaibhav1734** [comment]
So code like this
``` ruby
@redis.multi do |transaction|
     @prev = transaction.get("test")
end
@prev
```
should be written with the expectation of `FutureNotReady` error which may or may not be raised depending on when and whether EXEC succeeds. Yeah?

**Comment by byroot** [comment]
If the `multi` call didn't raise an error, then `@prev` was filled.

If not, it may be a bug, and I'm interested if you can reproduce it. Otherwise there's probably something in your code you are not telling me.

**Comment by gvaibhav1734** [comment]
I am able to reproduce it sometimes (3 times in 15 executions) with the part of code I have put up initially.

**Comment by byroot** [comment]
Then please extract it to an independent script I can run to investigate. The snippet you shared is not executable.

**Comment by gvaibhav1734** [comment]
Fair enough. I'll add an executable script.

**Comment by gvaibhav1734** [comment]
## Script
- Make sure host and port is changed to point to your local redis. I use the redis-alpine image with limited resources.
- To run `ruby redis_test.rb > output.log 2>&1`
- `cat output.log` to get output
- The script fails pretty reliably and it points to line 16.
``` ruby
# redis_test.rb
require 'redis'
@redis = Redis.new(host: "172.23.0.3", port: 6379)

def some_method(resource, expiry=10)
  result = @redis.multi do |pipeline|
    @prev = pipeline.setbit(resource, 2, 1)
    pipeline.expire(resource, expiry)
  end
  puts "#{Thread.current} #{"*" * 64}"
  puts "#{Thread.current} Redis multi #{result} #{resource}"
  puts "#{Thread.current} @prev object id #{@prev.__id__}"
  # Line of interest
  puts "#{Thread.current} Redis object #{(@prev.instance_eval{@object}).to_s}"
  puts "#{Thread.current} @prev object id #{@prev.__id__}"
  # Line of interest
  puts "#{Thread.current} @prev value #{@prev.value}"
  puts "#{Thread.current} #{"*" * 64}"
end

# The script (Ran this as an example in rspec)
(1..10).each do
  threads = []
  (1..1500).each do |i|
    threads << Thread.new do
      some_method("some_key_1", 4) if i%2 == 0
      some_method("some_key_2", 4) if i%2 != 0
    end
  end
  threads.map(&:join)
end
```

### Output
```
#<Thread:0x0055fb18d07d70> ****************************************************************
#<Thread:0x0055fb18d07d70> Redis multi [1, true] some_key_2
#<Thread:0x0055fb18d07d70> @prev object id 47268469517160
#<Thread:0x0055fb18d07d70> Redis object 1
#<Thread:0x0055fb18d07d70> @prev object id 47268469517160
#<Thread:0x0055fb18d07d70> @prev value 1
#<Thread:0x0055fb18d07d70> ****************************************************************
#<Thread:0x0055fb18d07c58> ****************************************************************
#<Thread:0x0055fb18d07c58> Redis multi [1, true] some_key_1
#<Thread:0x0055fb18d07c58> @prev object id 47268469470520
#<Thread:0x0055fb18d07c58> Redis object 1/home/vaibhavg/.rvm/gems/ruby-2.3.0/gems/redis-3.3.5/lib/redis/pipeline.rb:129:in `value': Value will be available once the pipeline executes. (Redis::FutureNotReady)
        from redis.rb:16:in `some_method'
        from redis.rb:25:in `block (3 levels) in <main>'

#<Thread:0x0055fb18d07c58> @prev object id 47268469423720
```

**Comment by byroot** [comment]
Well, yes if you use thread in conjunction with an instance variable, this will happen.

That's going on in your script is basically:

```ruby
# thread 1
redis.multi do |pipeline|
    @prev = pipeline.setbit(resource, 2, 1)
    # thread preempted here
    pipeline.expire(resource, expiry)
  end
```

```ruby
# thread 2
# resume here
puts "#{Thread.current} @prev value #{@prev.value}"
```

A quick fix (but still quite dirty could be:

```ruby
future = nil
redis.multi do |pipeline|
    future = pipeline.setbit(resource, 2, 1)
    # thread preempted here
    pipeline.expire(resource, expiry)
  end
@prev = future
```

This way you set the instance variable once the future is read.

You can even set `@prev = future.value`

So yeah, not a bug in Redis, but in your code
