### ISSUE TITLE
Can't get BITFIELD to work

### ISSUE THREAD

**Issue by mperham** [redis/redis-rb#1111]
I'm trying to use the [BITFIELD](https://redis.io/commands/bitfield/) command. Even the simplest example from the docs doesn't work with redis-rb and I didn't see it in the bitmaps module so I'm wondering if it was missed somehow? I'm running against Redis 7.0.0.

```
> r.bitfield "foo", "GET i8 16"
D, [2022-07-25T10:04:10.777985 #49123] DEBUG -- : [Redis] command=BITFIELD args="foo" "GET i8 16"
D, [2022-07-25T10:04:10.778505 #49123] DEBUG -- : [Redis] call_time=0.45 ms
/Users/mperham/.gem/ruby/3.0.3/gems/redis-4.7.1/lib/redis/client.rb:162:in `call': ERR syntax error (Redis::CommandError)
	from /Users/mperham/.gem/ruby/3.0.3/gems/redis-4.7.1/lib/redis.rb:269:in `block in send_command'
	from /Users/mperham/.gem/ruby/3.0.3/gems/redis-4.7.1/lib/redis.rb:268:in `synchronize'
	from /Users/mperham/.gem/ruby/3.0.3/gems/redis-4.7.1/lib/redis.rb:268:in `send_command'
	from /Users/mperham/.gem/ruby/3.0.3/gems/redis-4.7.1/lib/redis/commands.rb:239:in `method_missing'
	from (irb):19:in `<main>'
```

**Comment by byroot** [comment]
The arguments need to be passed independently: 

```ruby
>> r.bitfield "foo", "GET", "i8", "16"
=> [0]
```
