### ISSUE TITLE
Redis 7 support

### ISSUE THREAD

**Issue by voxik** [redis/redis-rb#1113]
Since Redis 7 landed in Fedora, we observe several failing test cases:

~~~
+ make BINARY=/usr/bin/redis-server REDIS_CLIENT=/usr/bin/redis-cli 'BUILD_DIR=${TMP}'
Run options: --seed 20345

# Running:

.....................................................................................................................................................................E.........E........................F...F..F.........................................................................................................................E......F..........................................Error running mock server: Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:8 
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/support/redis_mock.rb:87:in `gets'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/support/redis_mock.rb:87:in `block in start'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/support/redis_mock.rb:40:in `block in run'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/support/redis_mock.rb:36:in `loop'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/support/redis_mock.rb:36:in `run'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/support/redis_mock.rb:28:in `block in start'
.....................F............................................................................................................................................................F......................F.....F.............................................................................................................................................................................................................................F....................................................................................................................................................F....F...............................................................................................................................................................................E....FEE....E.E.EE.E.F.E...................................................................................................................................

Finished in 132.480076s, 9.7600 runs/s, 40.2929 assertions/s.

  1) Error:
TestRemoteServerControlCommands#test_info_commandstats:
NoMethodError: undefined method `[]' for nil:NilClass

      assert_equal '2', result['config']['calls']
                                        ^^^^^^^^^
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/remote_server_control_commands_test.rb:33:in `block in test_info_commandstats'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:158:in `target_version'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/remote_server_control_commands_test.rb:28:in `test_info_commandstats'

  2) Error:
TestRemoteServerControlCommands#test_debug:
Redis::CommandError: ERR DEBUG command not allowed. If the enable-debug-command option is set to "local", you can run it from a local connection, otherwise you need to set this option in the configuration file, and then restart the server.
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/client.rb:162:in `call'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:269:in `block in send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `synchronize'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/commands/server.rb:184:in `debug'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/remote_server_control_commands_test.rb:94:in `test_debug'

  3) Failure:
TestConnection#test_default_id_with_path_and_explicit_scheme [/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/connection_test.rb:64]:
Expected: "redis:///tmp/redis.sock/0"
  Actual: "unix:///tmp/redis.sock/0"

  4) Failure:
TestConnection#test_default_id_with_host_and_port_and_explicit_scheme [/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/connection_test.rb:54]:
Expected: "redis://host:1234/0"
  Actual: "foo://host:1234/0"

  5) Failure:
TestConnection#test_default_id_with_path [/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/connection_test.rb:59]:
Expected: "redis:///tmp/redis.sock/0"
  Actual: "unix:///tmp/redis.sock/0"

  6) Error:
TestDistributedRemoteServerControlCommands#test_info_commandstats:
NoMethodError: undefined method `[]' for nil:NilClass

        assert_equal '2', info['config']['calls'] # CONFIG RESETSTAT + CONFIG GET = twice
                                        ^^^^^^^^^
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/distributed_remote_server_control_commands_test.rb:37:in `block (2 levels) in test_info_commandstats'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/distributed_remote_server_control_commands_test.rb:36:in `each'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/distributed_remote_server_control_commands_test.rb:36:in `block in test_info_commandstats'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:158:in `target_version'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/distributed_remote_server_control_commands_test.rb:30:in `test_info_commandstats'

  7) Failure:
TestClusterAbnormalState#test_raising_error_when_nodes_are_not_cluster_mode [/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/cluster_abnormal_state_test.rb:52]:
Redis client could not connect to any cluster nodes.
[Redis::CannotConnectError] exception expected, not
Class: <Redis::Cluster::InitialSetupError>
Message: <"Redis client could not fetch cluster information: ERR This instance has cluster support disabled">
---Backtrace---
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/cluster/slot_loader.rb:21:in `load'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/cluster.rb:116:in `fetch_cluster_info!'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/cluster.rb:26:in `initialize'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:86:in `new'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:86:in `initialize'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:417:in `new'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:417:in `_new_client'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:324:in `build_another_client'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/cluster_abnormal_state_test.rb:53:in `block in test_raising_error_when_nodes_are_not_cluster_mode'
---------------

  8) Failure:
TestClusterClientKeyHashTags#test_cannot_build_details_from_bad_urls [/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/cluster_client_key_hash_tags_test.rb:98]:
[Redis::CannotConnectError] exception expected, not
Class: <Redis::Cluster::InitialSetupError>
Message: <"Redis client could not fetch cluster information: Error connecting to Redis on 127.0.0.1:7006 (Errno::ECONNREFUSED)">
---Backtrace---
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/cluster/command_loader.rb:21:in `load'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/cluster_client_key_hash_tags_test.rb:12:in `build_described_class'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/cluster_client_key_hash_tags_test.rb:99:in `block in test_cannot_build_details_from_bad_urls'
---------------

  9) Failure:
TestClusterCommandsOnServer#test_config_get [/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/cluster_commands_on_server_test.rb:109]:
--- expected
+++ actual
@@ -1 +1 @@
-["hash-max-ziplist-entries", "set-max-intset-entries", "zset-max-ziplist-entries"]
+["hash-max-listpack-entries", "hash-max-ziplist-entries", "set-max-intset-entries", "zset-max-listpack-entries", "zset-max-ziplist-entries"]


 10) Failure:
TestClusterCommandsOnServer#test_command_info [/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/cluster_commands_on_server_test.rb:99]:
--- expected
+++ actual
@@ -1 +1 @@
-[["get", 2, ["readonly", "fast"], 1, 1, 1, ["@read", "@string", "@fast"]], ["set", -3, ["write", "denyoom"], 1, 1, 1, ["@write", "@string", "@slow"]], ["eval", -3, ["noscript", "skip_monitor", "may_replicate", "movablekeys"], 0, 0, 0, ["@slow", "@scripting"]]]
+[["get", 2, ["readonly", "fast"], 1, 1, 1, ["@read", "@string", "@fast"], [], [["flags", ["RO", "access"], "begin_search", ["type", "index", "spec", ["index", 1]], "find_keys", ["type", "range", "spec", ["lastkey", 0, "keystep", 1, "limit", 0]]]], []], ["set", -3, ["write", "denyoom"], 1, 1, 1, ["@write", "@string", "@slow"], [], [["notes", "RW and ACCESS due to the optional `GET` argument", "flags", ["RW", "access", "update", "variable_flags"], "begin_search", ["type", "index", "spec", ["index", 1]], "find_keys", ["type", "range", "spec", ["lastkey", 0, "keystep", 1, "limit", 0]]]], []], ["eval", -3, ["noscript", "stale", "skip_monitor", "no_mandatory_keys", "movablekeys"], 0, 0, 0, ["@slow", "@scripting"], [], [["notes", "We cannot tell how the keys will be used so we assume the worst, RW and UPDATE", "flags", ["RW", "access", "update"], "begin_search", ["type", "index", "spec", ["index", 2]], "find_keys", ["type", "keynum", "spec", ["keynumidx", 0, "firstkey", 1, "keystep", 1]]]], []]]


 11) Failure:
TestClusterCommandsOnServer#test_client_list [/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/cluster_commands_on_server_test.rb:48]:
--- expected
+++ actual
@@ -1 +1 @@
-["addr", "age", "argv-mem", "cmd", "db", "events", "fd", "flags", "id", "idle", "laddr", "multi", "name", "obl", "oll", "omem", "psub", "qbuf", "qbuf-free", "redir", "sub", "tot-mem", "user"]
+["addr", "age", "argv-mem", "cmd", "db", "events", "fd", "flags", "id", "idle", "laddr", "multi", "multi-mem", "name", "obl", "oll", "omem", "psub", "qbuf", "qbuf-free", "rbp", "rbs", "redir", "resp", "ssub", "sub", "tot-mem", "user"]


 12) Failure:
TestClusterClientInternals#test_acl_auth_failure [/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/cluster_client_internals_test.rb:90]:
[Redis::CannotConnectError] exception expected, not
Class: <Redis::Cluster::InitialSetupError>
Message: <"Redis client could not fetch cluster information: WRONGPASS invalid username-password pair or user is disabled.">
---Backtrace---
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/cluster/slot_loader.rb:21:in `load'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/cluster.rb:116:in `fetch_cluster_info!'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/cluster.rb:26:in `initialize'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:86:in `new'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:86:in `initialize'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:417:in `new'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:417:in `_new_client'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/cluster_client_internals_test.rb:91:in `block (3 levels) in test_acl_auth_failure'
---------------

 13) Failure:
TestClusterClientOptions#test_client_does_not_accept_db_specified_url [/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/cluster_client_options_test.rb:82]:
Could not connect to any nodes.
[Redis::CannotConnectError] exception expected, not
Class: <Redis::Cluster::InitialSetupError>
Message: <"Redis client could not fetch cluster information: ERR SELECT is not allowed in cluster mode">
---Backtrace---
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/cluster/slot_loader.rb:21:in `load'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/cluster.rb:116:in `fetch_cluster_info!'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/cluster.rb:26:in `initialize'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:86:in `new'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:86:in `initialize'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:417:in `new'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:417:in `_new_client'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:324:in `build_another_client'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/cluster_client_options_test.rb:83:in `block in test_client_does_not_accept_db_specified_url'
---------------

 14) Failure:
TestClusterClientOptions#test_client_does_not_accept_unconnectable_node_url_only [/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/cluster_client_options_test.rb:94]:
Could not connect to any nodes.
[Redis::CannotConnectError] exception expected, not
Class: <Redis::Cluster::InitialSetupError>
Message: <"Redis client could not fetch cluster information: Error connecting to Redis on 127.0.0.1:7006 (Errno::ECONNREFUSED)">
---Backtrace---
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/cluster/slot_loader.rb:21:in `load'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/cluster.rb:116:in `fetch_cluster_info!'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/cluster.rb:26:in `initialize'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:86:in `new'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:86:in `initialize'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:417:in `new'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:417:in `_new_client'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:324:in `build_another_client'
/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/cluster_client_options_test.rb:95:in `block in test_client_does_not_accept_unconnectable_node_url_only'
---------------

 15) Error:
TestScanning#test_scan_each_block_match:
Redis::CommandError: ERR DEBUG command not allowed. If the enable-debug-command option is set to "local", you can run it from a local connection, otherwise you need to set this option in the configuration file, and then restart the server.
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/client.rb:162:in `call'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:269:in `block in send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `synchronize'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/commands/server.rb:184:in `debug'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:131:in `block in test_scan_each_block_match'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:158:in `target_version'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:130:in `test_scan_each_block_match'

 16) Failure:
TestScanning#test_zscan_with_encoding [/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:348]:
--- expected
+++ actual
@@ -1,3 +1 @@
-# encoding: US-ASCII
-#    valid: true
-"ziplist"
+"listpack"


 17) Error:
TestScanning#test_scan_each_enumerator_match:
Redis::CommandError: ERR DEBUG command not allowed. If the enable-debug-command option is set to "local", you can run it from a local connection, otherwise you need to set this option in the configuration file, and then restart the server.
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/client.rb:162:in `call'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:269:in `block in send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `synchronize'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/commands/server.rb:184:in `debug'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:91:in `block in test_scan_each_enumerator_match'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:158:in `target_version'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:90:in `test_scan_each_enumerator_match'

 18) Error:
TestScanning#test_scan_each_enumerator:
Redis::CommandError: ERR DEBUG command not allowed. If the enable-debug-command option is set to "local", you can run it from a local connection, otherwise you need to set this option in the configuration file, and then restart the server.
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/client.rb:162:in `call'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:269:in `block in send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `synchronize'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/commands/server.rb:184:in `debug'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:77:in `block in test_scan_each_enumerator'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:158:in `target_version'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:76:in `test_scan_each_enumerator'

 19) Error:
TestScanning#test_scan_type:
Redis::CommandError: ERR DEBUG command not allowed. If the enable-debug-command option is set to "local", you can run it from a local connection, otherwise you need to set this option in the configuration file, and then restart the server.
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/client.rb:162:in `call'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:269:in `block in send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `synchronize'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/commands/server.rb:184:in `debug'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:58:in `block in test_scan_type'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:158:in `target_version'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:57:in `test_scan_type'

 20) Error:
TestScanning#test_scan_basic:
Redis::CommandError: ERR DEBUG command not allowed. If the enable-debug-command option is set to "local", you can run it from a local connection, otherwise you need to set this option in the configuration file, and then restart the server.
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/client.rb:162:in `call'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:269:in `block in send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `synchronize'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/commands/server.rb:184:in `debug'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:10:in `block in test_scan_basic'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:158:in `target_version'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:9:in `test_scan_basic'

 21) Error:
TestScanning#test_scan_each_enumerator_type:
Redis::CommandError: ERR DEBUG command not allowed. If the enable-debug-command option is set to "local", you can run it from a local connection, otherwise you need to set this option in the configuration file, and then restart the server.
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/client.rb:162:in `call'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:269:in `block in send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `synchronize'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/commands/server.rb:184:in `debug'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:102:in `block in test_scan_each_enumerator_type'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:158:in `target_version'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:101:in `test_scan_each_enumerator_type'

 22) Error:
TestScanning#test_scan_each_block:
Redis::CommandError: ERR DEBUG command not allowed. If the enable-debug-command option is set to "local", you can run it from a local connection, otherwise you need to set this option in the configuration file, and then restart the server.
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/client.rb:162:in `call'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:269:in `block in send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `synchronize'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/commands/server.rb:184:in `debug'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:116:in `block in test_scan_each_block'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:158:in `target_version'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:115:in `test_scan_each_block'

 23) Error:
TestScanning#test_scan_count:
Redis::CommandError: ERR DEBUG command not allowed. If the enable-debug-command option is set to "local", you can run it from a local connection, otherwise you need to set this option in the configuration file, and then restart the server.
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/client.rb:162:in `call'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:269:in `block in send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `synchronize'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/commands/server.rb:184:in `debug'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:26:in `block in test_scan_count'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:158:in `target_version'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:25:in `test_scan_count'

 24) Failure:
TestScanning#test_hscan_with_encoding [/builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:249]:
--- expected
+++ actual
@@ -1,3 +1 @@
-# encoding: US-ASCII
-#    valid: true
-"ziplist"
+"listpack"


 25) Error:
TestScanning#test_scan_match:
Redis::CommandError: ERR DEBUG command not allowed. If the enable-debug-command option is set to "local", you can run it from a local connection, otherwise you need to set this option in the configuration file, and then restart the server.
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/client.rb:162:in `call'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:269:in `block in send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `synchronize'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis.rb:268:in `send_command'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/lib/redis/commands/server.rb:184:in `debug'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:42:in `block in test_scan_match'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/helper.rb:158:in `target_version'
    /builddir/build/BUILD/redis-4.7.1/usr/share/gems/gems/redis-4.7.1/test/scanning_test.rb:41:in `test_scan_match'

1293 runs, 5338 assertions, 13 failures, 12 errors, 0 skips
make: *** [makefile:39: test] Error 1
~~~

So far, I have identified workaround for the _ERR DEBUG command not allowed_ issue:

~~~
$ sed -i '/unixsocket/i \
               --enable-debug-command  local\\' \
  makefile
~~~

which improves the situation a bit:

~~~
... snip ...

1293 runs, 5349 assertions, 13 failures, 2 errors, 0 skips
~~~

And now I wonder, is there any timeline for Redis 7 support?

**Comment by byroot** [comment]
I updated CI to test against redis 7.0. As expected this was all test only issues, redis-rb doesn't need any update to be compatible with Redis 7.

**Comment by voxik** [comment]
Thx a lot for the updates. Going to give it a try.
