### ISSUE TITLE
Redis nomethod error since Redis 5.0.0

### ISSUE THREAD

**Issue by mjerem34** [redis/redis-rb#1140]
Hello, my build failed due to update of Redis.

The build log : 
```
-----> Building on the Heroku-20 stack

-----> Using buildpacks:

       1. https://github.com/gaffneyc/heroku-buildpack-jemalloc.git

       2. heroku/ruby

-----> jemalloc app detected

-----> jemalloc: Vendoring 5.2.1

-----> jemalloc: Building runtime environment

-----> Ruby app detected

-----> Installing bundler 2.3.10

-----> Removing BUNDLED WITH version in the Gemfile.lock

-----> Compiling Ruby/Rails

-----> Using Ruby version: ruby-2.7.5

###### WARNING:

       Removing `Gemfile.lock` because it was generated on Windows.

       Bundler will do a full resolve so native gems are handled properly.

       This may result in unexpected gem versions being used in your app.

       In rare occasions Bundler may not be able to resolve your dependencies at all.

       

       https://devcenter.heroku.com/articles/bundler-windows-gemfile

-----> Installing dependencies using bundler 2.3.10

       Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin bundle install -j4

       Fetching gem metadata from https://rubygems.org/.........

       Resolving dependencies.............

       Using rake 13.0.6

       Using zeitwerk 2.6.0

       Using builder 3.2.4

       Using concurrent-ruby 1.1.10

       Using minitest 5.16.3

       Using erubi 1.11.0

       Using racc 1.6.0

       Using rack 2.2.4

       Using nio4r 2.5.8

       Using websocket-extensions 0.1.5

       Using marcel 1.0.2

       Using mini_mime 1.1.2

       Using public_suffix 5.0.0

       Using aggregate 0.2.3

       Using httpclient 2.8.3

       Using crass 1.0.6

       Using json 2.6.2

       Using aws-eventstream 1.2.0

       Using ast 2.4.2

       Using aws-partitions 1.622.0

       Using jmespath 1.6.1

       Using htmlentities 4.3.4

       Using rubyzip 2.3.2

       Using bcrypt 3.1.18

       Using msgpack 1.5.6

       Using bundler 2.3.10

       Using cocoon 1.2.15

       Using connection_pool 2.2.5

       Using i18n_data 0.11.0

       Using sixarm_ruby_unaccent 1.2.0

       Using unicode_utils 1.4.0

       Using dalli 3.2.2

       Using declarative 0.0.20

       Using orm_adapter 0.5.0

       Using method_source 0.9.2

       Using thor 1.2.1

       Using dynoscale_ruby 1.0.1

       Using erubis 2.7.0

       Using execjs 2.8.1

       Using faraday-em_http 1.0.0

       Using faraday-em_synchrony 1.0.0

       Using excon 0.92.4

       Using faraday-httpclient 1.0.1

       Using multipart-post 2.2.3

       Using faraday-excon 1.1.0

       Using faraday-net_http 1.0.1

       Using faraday-net_http_persistent 1.2.0

       Using faraday-patron 1.0.0

       Using faraday-rack 1.0.0

       Using faraday-retry 1.0.3

       Using ruby2_keywords 0.0.5

       Using ffi 1.15.5

       Using flutie 2.2.0

       Using geocoder 1.8.0

       Using gli 2.21.0

       Using jwt 2.5.0

       Using memoist 0.16.2

       Using multi_json 1.15.0

       Using os 1.1.4

       Using trailblazer-option 0.1.2

       Using raabro 1.4.0

       Using uber 0.1.0

       Using retriable 3.1.2

       Using rexml 3.2.5

       Using webrick 1.7.0

       Using mime-types-data 3.2022.0105

       Using multi_xml 0.6.0

       Using temple 0.8.2

       Using tilt 2.0.11

       Using hashie 5.0.0

       Using moneta 1.0.0

       Using hetchy 1.0.0

       Using ice_cube 0.16.4

       Using newrelic_rpm 6.13.1

       Using rate_throttle_client 0.1.2

       Using pg 1.4.3

       Using stripe 7.1.0

       Using wkhtmltopdf-heroku 2.12.5.0

       Using i18n 1.12.0

       Using tzinfo 2.0.5

       Using nokogiri 1.13.8 (x86_64-linux)

       Using rack-test 2.0.2

       Using websocket-driver 0.7.5

       Using mail 2.7.1

       Using addressable 2.8.1

       Using bugsnag 6.21.0

       Using warden 1.2.9

       Using sprockets 4.1.1

       Using puma 4.3.12

       Using rack-cors 1.1.1

       Using algoliasearch 1.27.5

       Using bootsnap 1.13.0

       Using countries 3.1.0

       Using sort_alphabetical 1.1.0

       Fetching redis-client 0.7.1

       Using rodf 1.2.0

       Using aws-sigv4 1.5.1

       Using faraday-multipart 1.0.4

       Using sassc 2.4.0

       Using representable 3.2.0

       Using mime-types 3.4.1

       Using haml 5.2.2

       Using icalendar 2.8.0

       Using parser 3.1.2.1

       Using heroics 0.1.2

       Using loofah 2.18.0

       Using caxlsx 3.2.0

       Using algoliasearch-rails 1.24.1

       Using country_select 4.0.0

       Using css_parser 1.11.0

       Using handlebars_assets 0.23.9

       Using i18n-js 3.9.2

       Using activesupport 6.1.4.6

       Using et-orbi 1.2.7

       Using faraday 1.10.2

       Using httparty 0.18.1

       Using platform-api 2.3.0

       Using scout_apm 2.6.10

       Using aws-sdk-core 3.136.0

       Using rails-html-sanitizer 1.4.3

       Using rails-dom-testing 2.0.3

       Using actionview 6.1.4.6

       Using globalid 1.0.0

       Using activemodel 6.1.4.6

       Using aws-sdk-kms 1.58.0

       Using axlsx_styler 1.1.0

       Using faraday_middleware 1.2.0

       Using fugit 1.6.0

       Using signet 0.17.0

       Using google_places 2.0.0

       Using hubspot-ruby 0.9.0

       Using jsonapi-serializer 2.2.0

       Using librato-metrics 2.1.2

       Using pagy 5.10.1

       Using premailer 1.16.0

       Using vamoos 0.2.0

       Using wicked_pdf 1.4.0

       Using actionpack 6.1.4.6

       Using activejob 6.1.4.6

       Using activerecord 6.1.4.6

       Using aws-sdk-s3 1.114.0

       Using googleauth 1.2.0

       Using librato-rack 2.0.5

       Using slack-ruby-client 0.14.6

       Using spreadsheet_architect 4.2.0

       Using actioncable 6.1.4.6

       Using ancestry 4.1.0

       Using audited 5.0.2

       Using auto_strip_attributes 2.6.0

       Using railties 6.1.4.6

       Using sprockets-rails 3.3.0

       Using google-apis-core 0.7.0

       Using simple_form 5.1.0

       Using activestorage 6.1.4.6

       Using actionmailer 6.1.4.6

       Using responders 3.0.1

       Using google-apis-admin_directory_v1 0.31.0

       Using i18n-country-translations 1.4.1

       Using jquery-rails 4.5.0

       Using librato-rails 2.1.0

       Using rails-i18n 6.0.0

       Using sassc-rails 2.1.2

       Using scenic 1.6.0

       Using actionmailbox 6.1.4.6

       Using actiontext 6.1.4.6

       Using devise 4.8.1

       Using sass-rails 6.0.0

       Using devise-i18n 1.10.2

       Using devise_invitable 2.0.6

       Using premailer-rails 1.11.1

       Using rails 6.1.4.6

       Using devise_token_auth 1.2.0

       Installing redis-client 0.7.1

       Fetching redis 5.0.0

       Installing redis 5.0.0

       Using sidekiq 6.4.2

       Using sidekiq-cron 1.4.0

       Bundle complete! 73 Gemfile dependencies, 175 gems now installed.

       Gems in the groups 'development' and 'test' were not installed.

       Bundled gems are installed into `./vendor/bundle`

       Bundle completed (6.18s)

       Cleaning up the bundler cache.

       Removing redis (4.8.0)

-----> Installing node-v16.13.1-linux-x64

-----> Detecting rake tasks

-----> Preparing app for Rails asset pipeline

       Running: rake assets:precompile

       rake aborted!

       NoMethodError: undefined method `drivers' for Redis::Commands::Connection:Module

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/redis_connection.rb:82:in `client_opts'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/redis_connection.rb:56:in `build_client'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq/redis_connection.rb:35:in `block in create'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:169:in `try_create'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:73:in `block (2 levels) in pop'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:69:in `loop'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:69:in `block in pop'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:68:in `synchronize'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:68:in `pop'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:78:in `checkout'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:60:in `block in with'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.4.2/lib/sidekiq.rb:92:in `redis'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/sidekiq-cron-1.4.0/lib/sidekiq/cron/job.rb:364:in `status_from_redis'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/sidekiq-cron-1.4.0/lib/sidekiq/cron/job.rb:275:in `initialize'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/sidekiq-cron-1.4.0/lib/sidekiq/cron/job.rb:190:in `new'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/sidekiq-cron-1.4.0/lib/sidekiq/cron/job.rb:190:in `block in load_from_array'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/sidekiq-cron-1.4.0/lib/sidekiq/cron/job.rb:189:in `each'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/sidekiq-cron-1.4.0/lib/sidekiq/cron/job.rb:189:in `load_from_array'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/sidekiq-cron-1.4.0/lib/sidekiq/cron/job.rb:160:in `load_from_hash'

       /tmp/build_9e3fc29c/config/initializers/sidekiq_cron.rb:79:in `<main>'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:326:in `load'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:326:in `block in load'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:299:in `load_dependency'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:326:in `load'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/engine.rb:681:in `block in load_config_initializer'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/notifications.rb:205:in `instrument'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/engine.rb:680:in `load_config_initializer'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/engine.rb:633:in `each'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/engine.rb:633:in `block in <class:Engine>'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:32:in `instance_exec'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:32:in `run'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:61:in `block in run_initializers'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:50:in `each'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:50:in `tsort_each_child'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:60:in `run_initializers'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/application.rb:391:in `initialize!'

       /tmp/build_9e3fc29c/config/environment.rb:7:in `<main>'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `block in require'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:299:in `load_dependency'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `require'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/application.rb:367:in `require_environment!'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/application.rb:533:in `block in run_tasks_blocks'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/bugsnag-6.21.0/lib/bugsnag/integrations/rake.rb:20:in `execute'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/sprockets-rails-3.3.0/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'

       /tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/bugsnag-6.21.0/lib/bugsnag/integrations/rake.rb:20:in `execute'

       Tasks: TOP => environment

       (See full trace by running task with --trace)

       [Scout] [08/29/22 09:11:22 +0000 run.4602 (365)] WARN : Exception loading instruments:

       [Scout] [08/29/22 09:11:22 +0000 run.4602 (365)] WARN : undefined method `call' for class `Redis::Client'

       Did you mean?  caller

       [Scout] [08/29/22 09:11:22 +0000 run.4602 (365)] WARN : ["/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/scout_apm-2.6.10/lib/scout_apm/instruments/redis.rb:36:in `alias_method'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/scout_apm-2.6.10/lib/scout_apm/instruments/redis.rb:36:in `block in install'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/scout_apm-2.6.10/lib/scout_apm/instruments/redis.rb:25:in `class_eval'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/scout_apm-2.6.10/lib/scout_apm/instruments/redis.rb:25:in `install'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/scout_apm-2.6.10/lib/scout_apm/instrument_manager.rb:63:in `install_instrument'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/scout_apm-2.6.10/lib/scout_apm/instrument_manager.rb:35:in `install!'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/scout_apm-2.6.10/lib/scout_apm/agent.rb:41:in `install'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/scout_apm-2.6.10/lib/scout_apm.rb:209:in `block in <class:Railtie>'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:32:in `instance_exec'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:32:in `run'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:61:in `block in run_initializers'", "/tmp/build_9e3fc29c/vendor/ruby-2.7.5/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'", "/tmp/build_9e3fc29c/vendor/ruby-2.7.5/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'", "/tmp/build_9e3fc29c/vendor/ruby-2.7.5/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'", "/tmp/build_9e3fc29c/vendor/ruby-2.7.5/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'", "/tmp/build_9e3fc29c/vendor/ruby-2.7.5/lib/ruby/2.7.0/tsort.rb:347:in `each'", "/tmp/build_9e3fc29c/vendor/ruby-2.7.5/lib/ruby/2.7.0/tsort.rb:347:in `call'", "/tmp/build_9e3fc29c/vendor/ruby-2.7.5/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'", "/tmp/build_9e3fc29c/vendor/ruby-2.7.5/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'", "/tmp/build_9e3fc29c/vendor/ruby-2.7.5/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:60:in `run_initializers'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/application.rb:391:in `initialize!'", "/tmp/build_9e3fc29c/config/environment.rb:7:in `<main>'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `block in require'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:299:in `load_dependency'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `require'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/application.rb:367:in `require_environment!'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/application.rb:533:in `block in run_tasks_blocks'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/bugsnag-6.21.0/lib/bugsnag/integrations/rake.rb:20:in `execute'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/sprockets-rails-3.3.0/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/bugsnag-6.21.0/lib/bugsnag/integrations/rake.rb:20:in `execute'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'", "/tmp/build_9e3fc29c/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'", "/tmp/build_9e3fc29c/bin/rake:9:in `<main>'"]

       I, [2022-08-29T09:11:22.671430 #365]  INFO -- [Bugsnag]: Notifying https://notify.bugsnag.com of NoMethodError

       I, [2022-08-29T09:11:22.696946 #365]  INFO -- [Bugsnag]: Notifying https://notify.bugsnag.com of NoMethodError

       W, [2022-08-29T09:11:22.697372 #365]  WARN -- [Bugsnag]: Waiting for 1 outstanding request(s)

 !

 !     Precompiling assets failed.

 !

 !     Push rejected, failed to compile Ruby app.

 !     Push failed
```

I fixed build by fixing Redis to 4.8.0.

**Comment by byroot** [comment]
Yes, sidekiq poke in the internals, it would have been fixed with https://github.com/mperham/sidekiq/pull/5489, but Mike prefered to lock redis down: https://github.com/mperham/sidekiq/commit/d566154107e6543ccb42e0d2e7eddfb529f0933e

However I thought this change was released already, but apparently it wasn't.

I'm tempted to add that method back as a noop.
