### ISSUE TITLE
Unsupported command argument type: NilClass (TypeError)

### ISSUE THREAD

**Issue by sirfilip** [redis/redis-rb#1144]
```ruby
irb(main):001:0> require 'redis'
=> true
irb(main):002:0> r = Redis.new
=> #<Redis client v5.0.1 for redis://localhost:6379/0>
irb(main):003:0> r.client
/Users/filip/.gem/ruby/3.1.2/gems/redis-client-0.7.1/lib/redis_client/command_builder.rb:37:in `block in generate': Unsupported command argument type: NilClass (TypeError)
        from /Users/filip/.gem/ruby/3.1.2/gems/redis-client-0.7.1/lib/redis_client/command_builder.rb:28:in `map!'
        from /Users/filip/.gem/ruby/3.1.2/gems/redis-client-0.7.1/lib/redis_client/command_builder.rb:28:in `generate'
        from /Users/filip/.gem/ruby/3.1.2/gems/redis-client-0.7.1/lib/redis_client.rb:201:in `call_v'
        from /Users/filip/.gem/ruby/3.1.2/gems/redis-5.0.1/lib/redis/client.rb:79:in `call_v'
        from /Users/filip/.gem/ruby/3.1.2/gems/redis-5.0.1/lib/redis.rb:167:in `block in send_command'
        from /Users/filip/.gem/ruby/3.1.2/gems/redis-5.0.1/lib/redis.rb:166:in `synchronize'
        from /Users/filip/.gem/ruby/3.1.2/gems/redis-5.0.1/lib/redis.rb:166:in `send_command'
        from /Users/filip/.gem/ruby/3.1.2/gems/redis-5.0.1/lib/redis/commands/server.rb:40:in `client'
        from (irb):4:in `<main>'
        from /Users/filip/.rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
        from /Users/filip/.rubies/ruby-3.1.2/bin/irb:25:in `load'
        from /Users/filip/.rubies/ruby-3.1.2/bin/irb:25:in `<main>'
```

**Comment by byroot** [comment]
I'll fix this so that it fails more cleanly, but note that this was never a valid command, e.g. with 4.x:

```ruby
>> Redis::VERSION
=> "4.6.0"
>> Redis.new.client
ERR unknown subcommand ''. Try CLIENT HELP. (Redis::CommandError)
```

`Redis#client` must be provided at least one argument:

```
$ redis-cli
127.0.0.1:6379> CLIENT
(error) ERR wrong number of arguments for 'client' command
```

**Comment by byroot** [comment]
Fixed on master. However given that it's not a valid command anyway, I won't release the fix immediately.
