### ISSUE TITLE
sentinels: [] connection settings are broken after usage of regis-client lib - no mention in version 5 upgrade guide.

### ISSUE THREAD

**Issue by NielsKSchjoedt** [redis/redis-rb#1183]
The sentinels require a `name:` https://github.com/redis-rb/redis-client/blob/9513681301f5f2b3e789356d88fafa19e948f7a3/lib/redis_client/sentinel_config.rb#L10 argument which cannot be set on `Redis.new(sentinels: ...)`

**Comment by NielsKSchjoedt** [comment]
If `name:` is set on `Redis.new(name: "something", sentinels: [...])` then I get:

```
ArgumentError: wrong number of arguments (given 1, expected 0)
redis-client-0.13.0/lib/redis_client/config.rb:21:in `initialize'
redis-client-0.13.0/lib/redis_client/config.rb:182:in `initialize'
redis-client-0.13.0/lib/redis_client/sentinel_config.rb:34:in `new'
redis-client-0.13.0/lib/redis_client/sentinel_config.rb:34:in `block in initialize'
redis-client-0.13.0/lib/redis_client/sentinel_config.rb:29:in `map'
redis-client-0.13.0/lib/redis_client/sentinel_config.rb:29:in `initialize'
redis-client-0.13.0/lib/redis_client.rb:147:in `new'
redis-client-0.13.0/lib/redis_client.rb:147:in `sentinel'
redis-5.0.6/lib/redis/client.rb:27:in `sentinel'
redis-5.0.6/lib/redis.rb:155:in `initialize_client'
redis-5.0.6/lib/redis.rb:73:in `initialize'
``

**Comment by byroot** [comment]
It's documented in the README: https://github.com/redis/redis-rb#sentinel-support

```ruby
Redis.new(url: "redis://something", sentinels: [...])
```

I'll see about either supporting the old option, or better pointing this in the Changelog.

**Comment by NielsKSchjoedt** [comment]
@byroot thx - so you are saying that a URL must be provided? I cannot just have `Redis.new(name: "mymaster", host: "localhost", port: 6379, sentinels: [...])` when using sentinels?

**Comment by byroot** [comment]
`host:` and `port:` make no sense for sentinel, they were never considered.

As for the name, it has to be passed as an url: `Redis.new(url: "redis://my-sentinel-name", sentinels: [])`.

**Comment by NielsKSchjoedt** [comment]
Okay, maybe I'm getting this all wrong, but when I do:

```ruby
Redis.new(db: 0, sentinels: [{"host"=>"localhost", "port"=>24352}], url: "redis://primary-sentinel"})
```

I get:

```
/Users/nk/.rvm/gems/ruby-2.7.2@rails6/gems/redis-client-0.13.0/lib/redis_client/config.rb:21:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /Users/nk/.rvm/gems/ruby-2.7.2@rails6/gems/redis-client-0.13.0/lib/redis_client/config.rb:182:in `initialize'
	from /Users/nk/.rvm/gems/ruby-2.7.2@rails6/gems/redis-client-0.13.0/lib/redis_client/sentinel_config.rb:34:in `new'
	from /Users/nk/.rvm/gems/ruby-2.7.2@rails6/gems/redis-client-0.13.0/lib/redis_client/sentinel_config.rb:34:in `block in initialize'
	from /Users/nk/.rvm/gems/ruby-2.7.2@rails6/gems/redis-client-0.13.0/lib/redis_client/sentinel_config.rb:29:in `map'
	from /Users/nk/.rvm/gems/ruby-2.7.2@rails6/gems/redis-client-0.13.0/lib/redis_client/sentinel_config.rb:29:in `initialize'
	from /Users/nk/.rvm/gems/ruby-2.7.2@rails6/gems/redis-client-0.13.0/lib/redis_client.rb:147:in `new'
	from /Users/nk/.rvm/gems/ruby-2.7.2@rails6/gems/redis-client-0.13.0/lib/redis_client.rb:147:in `sentinel'
	from /Users/nk/.rvm/gems/ruby-2.7.2@rails6/gems/redis-5.0.6/lib/redis/client.rb:27:in `sentinel'
	from /Users/nk/.rvm/gems/ruby-2.7.2@rails6/gems/redis-5.0.6/lib/redis.rb:155:in `initialize_client'
```

What am I doing wrong here...

**Comment by NielsKSchjoedt** [comment]
Okay, I got it. Not `"host"=>` but `host:` 🤦‍♂️sry. It works with `name: ` instead of `url:` too...
