### ISSUE TITLE
Sentinel tests fail with redis-client 0.15.0

### ISSUE THREAD

**Issue by voxik** [redis/redis-rb#1209]
~~~
  1) Error:
SentinelCommandsTest#test_sentinel_command_masters:
NoMethodError: undefined method `call' for #<Redis::Client redis://127.0.0.1:6400/0>
    /home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.5.0/gems/redis-client-0.15.0/lib/redis_client/sentinel_config.rb:128:in `block in resolve_master'
    /home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.5.0/gems/redis-client-0.15.0/lib/redis_client/sentinel_config.rb:170:in `block in each_sentinel'
    /home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.5.0/gems/redis-client-0.15.0/lib/redis_client/sentinel_config.rb:166:in `each'
    /home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.5.0/gems/redis-client-0.15.0/lib/redis_client/sentinel_config.rb:166:in `each_sentinel'
    /home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.5.0/gems/redis-client-0.15.0/lib/redis_client/sentinel_config.rb:127:in `resolve_master'
    /home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.5.0/gems/redis-client-0.15.0/lib/redis_client/sentinel_config.rb:119:in `block in config'
    /home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.5.0/gems/redis-client-0.15.0/lib/redis_client/sentinel_config.rb:117:in `synchronize'
    /home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.5.0/gems/redis-client-0.15.0/lib/redis_client/sentinel_config.rb:117:in `config'
    /home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.5.0/gems/redis-client-0.15.0/lib/redis_client/sentinel_config.rb:69:in `host'
    /home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.5.0/gems/redis-client-0.15.0/lib/redis_client/ruby_connection.rb:126:in `connect'
    /home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.5.0/gems/redis-client-0.15.0/lib/redis_client/ruby_connection.rb:49:in `initialize'
    /home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.5.0/gems/redis-client-0.15.0/lib/redis_client.rb:685:in `new'
    /home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.5.0/gems/redis-client-0.15.0/lib/redis_client.rb:685:in `block in connect'
    /home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.5.0/gems/redis-client-0.15.0/lib/redis_client/middlewares.rb:12:in `connect'
    /home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.5.0/gems/redis-client-0.15.0/lib/redis_client.rb:684:in `connect'
    /home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.5.0/gems/redis-client-0.15.0/lib/redis_client.rb:671:in `raw_connection'
    /home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.5.0/gems/redis-client-0.15.0/lib/redis_client.rb:638:in `ensure_connected'
    /home/runner/work/redis-rb/redis-rb/vendor/bundle/ruby/2.5.0/gems/redis-client-0.15.0/lib/redis_client.rb:233:in `call_v'
    /home/runner/work/redis-rb/redis-rb/lib/redis/client.rb:73:in `call_v'
    /home/runner/work/redis-rb/redis-rb/lib/redis.rb:167:in `block in send_command'
    /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'
    /home/runner/work/redis-rb/redis-rb/lib/redis.rb:166:in `send_command'
    /home/runner/work/redis-rb/redis-rb/lib/redis/commands/connection.rb:37:in `select'
    /home/runner/work/redis-rb/redis-rb/test/helper.rb:112:in `init'
    /home/runner/work/redis-rb/redis-rb/test/helper.rb:99:in `setup'
~~~

See more in my test action run: https://github.com/voxik/redis-rb/actions/runs/5764537106/job/15628689955

**Comment by tomasmiguez** [comment]
We are having the same issue currently, and can't update the `redis-client` dependency in our applications due to it.
