### ISSUE TITLE
Unable to create redis cluster

### ISSUE THREAD

**Issue by nkroker** [redis/redis-rb#1252]
After upgrading to redis-5
I'm unable to create the redis cluster

```
[14] pry(main)> Redis::Cluster.new(nodes: ["redis://redishost:6379"])
Redis::Cluster::InitialSetupError: Redis client could not fetch cluster information: ERR This instance has cluster support disabled
from /usr/local/bundle/gems/redis-cluster-client-0.7.5/lib/redis_client/cluster/node.rb:133:in `load_info'
Caused by RedisClient::Cluster::InitialSetupError: Redis client could not fetch cluster information: ERR This instance has cluster support disabled
from /usr/local/bundle/gems/redis-cluster-client-0.7.5/lib/redis_client/cluster/node.rb:133:in `load_info'
```

But when I create a `Redis` instance It works only the clustering is not working
```
[1] pry(main)> Redis.new(url: "redis://redishost:6379").ping
=> "PONG"
```

I've followed this readme file 
https://github.com/redis/redis-rb/blob/master/cluster/README.md

**Comment by byroot** [comment]
> `ERR This instance has cluster support disabled`

This is a server error, likely has nothing to do with the gem or you upgrading.
