### ISSUE TITLE
Redis + Ruby 2.0.0(-p195 || -p0)

### ISSUE THREAD

**Issue by whoughton** [redis/redis-rb#341]
``` log
Redis::CommandError (ERR unknown command 'to_ary'):
  redis (3.0.4) lib/redis/client.rb:85:in `call'
  redis (3.0.4) lib/redis.rb:2240:in `block in method_missing'
  redis (3.0.4) lib/redis.rb:36:in `block in synchronize'
  /Users/whoughton/.rbenv/versions/2.0.0-p195/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
  redis (3.0.4) lib/redis.rb:36:in `synchronize'
  redis (3.0.4) lib/redis.rb:2239:in `method_missing'
  rack (1.4.5) lib/rack/session/abstract/id.rb:251:in `load_session'
```

Is the Redis gem not working with Ruby2? I'm seeing this error when just trying to do a Redis.new in a custom session class I am working on.

``` ruby
def get_session(env, session_id)
    Rails.logger.debug "\n-- get_session --\n#{__FILE__}\n env :: #{env.keys}\nsession_id :: #{session_id}\nrails app :: #{Rails.application.config.inspect}"
    redis = Redis.new
end
```

**Comment by orangeudav** [comment]
And how do you fix this issue?

**Comment by whoughton** [comment]
Honestly don't recall at this point, I'm sorry. I do know that I ended up moving back to cookie-based sessions, but don't think that this was the reason. I am using Redis successfully (not as a session store) elsewhere in the app with Ruby 2.1.5 though.
