### ISSUE TITLE
Unhandled ::Errno::ETIMEDOUT exception in lib/redis/connection/ruby.rb

### ISSUE THREAD

**Issue by timsatterfield** [redis/redis-rb#353]
Was my understanding that any connection problems would we encapsulated in the following error types:
::Redis::TimeoutError, ::Redis::ConnectionError, ::Redis::CannotConnectError

However I have run into ::Errno::ETIMEDOUT in version 3.0.1+

``` ruby
"/redis-3.0.1/lib/redis/connection/ruby.rb:120:in `connect_nonblock'",
"/redis-3.0.1/lib/redis/connection/ruby.rb:120:in `rescue in connect'",
"/redis-3.0.1/lib/redis/connection/ruby.rb:112:in `connect'",
"/redis-3.0.1/lib/redis/connection/ruby.rb:170:in `connect'",
"/redis-3.0.1/lib/redis/client.rb:257:in `establish_connection'",
"/redis-3.0.1/lib/redis/client.rb:63:in `connect'",
"/redis-3.0.1/lib/redis/client.rb:276:in `ensure_connected'",
"/redis-3.0.1/lib/redis/client.rb:167:in `block in process'",
"/redis-3.0.1/lib/redis/client.rb:242:in `logging'",
"/redis-3.0.1/lib/redis/client.rb:166:in `process'",
"/redis-3.0.1/lib/redis/client.rb:78:in `call'",
"/redis-3.0.1/lib/redis.rb:1767:in `block in hmget'",
"/redis-3.0.1/lib/redis.rb:36:in `block in synchronize'",
"/opt/ruby-1.9.2/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'",
"/redis-3.0.1/lib/redis.rb:36:in `synchronize'",
"/redis-3.0.1/lib/redis.rb:1766:in `hmget'",
"/redis-3.0.1/lib/redis.rb:1783:in `mapped_hmget'
```

**Comment by ioquatix** [comment]
I could reproduce this issue in a different code base. I'm still trying to figure out what's going on. I'm of the opinion that it shouldn't be possible with non-blocking sockets.
