### ISSUE TITLE
 ERR unknown command 'sentinel' (Redis::CommandError)

### ISSUE THREAD

**Issue by ArunSakthivel** [redis/redis-rb#533]
I'm facing issue connecting multiple redis host using "sentinels". Here is my code snippets

````
require "hiredis"
require "redis"
SENTINELS = [{:host => "127.0.0.1", :port => 6379}]
redis = Redis.new(:url => "redis://master.redis.com:6379/0", :sentinels => SENTINELS, :master_name => :master)
p redis.ping
````

Is the issue in gem or my code?

ERROR Log
`````
from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis/client.rb:556:in `block in resolve_master'
	from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis/client.rb:538:in `block in sentinel_detect'
	from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis/client.rb:530:in `each'
	from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis/client.rb:530:in `sentinel_detect'
	from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis/client.rb:555:in `resolve_master'
	from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis/client.rb:519:in `resolve'
	from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis/client.rb:317:in `establish_connection'
	from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis/client.rb:94:in `block in connect'
	from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis/client.rb:279:in `with_reconnect'
	from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis/client.rb:93:in `connect'
	from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis/client.rb:350:in `ensure_connected'
	from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis/client.rb:207:in `block in process'
	from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis/client.rb:292:in `logging'
	from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis/client.rb:206:in `process'
	from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
	from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis.rb:89:in `block in ping'
	from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
	from /home/rails/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis.rb:37:in `synchronize'
	from /home/rails/.rvm/gems/ruby-2.2.0@self_service_api/gems/redis-3.2.1/lib/redis.rb:88:in `ping'
	from test_redis.rb:8:in `<main>'

**Comment by djanowski** [comment]
What's your setup? Are you running Sentinels?

**Comment by ArunSakthivel** [comment]
Yes, I have running Sentinels. Here is my sentinels.conf file

````
sentinel monitor mymaster 127.0.0.1 26379 2
sentinel down-after-milliseconds mymaster 60000
sentinel config-epoch mymaster 0
sentinel leader-epoch mymaster 0
`````

**Comment by ArunSakthivel** [comment]
Now I have modified code like this,

````
SENTINELS = [{:host => "127.0.0.1", :port => 26379}]
redis = Redis.new(:url => "redis://mymaster", :sentinels => SENTINELS, :role => :master)
p redis.ping
`````

Now, I'm getting below error:

````
/home/rails/lib/redis/client.rb:512:in `check': Instance role mismatch. Expected master, got sentinel. (Redis::ConnectionError)
	from /home/rails/lib/redis/client.rb:97:in `block in connect'
	from /home/rails/lib/redis/client.rb:279:in `with_reconnect'
	from /home/rails/lib/redis/client.rb:93:in `connect'
	from /home/rails/lib/redis/client.rb:350:in `ensure_connected'
	from /home/rails/lib/redis/client.rb:207:in `block in process'
	from /home/rails/lib/redis/client.rb:292:in `logging'
	from /home/rails/lib/redis/client.rb:206:in `process'
	from /home/rails/lib/redis/client.rb:112:in `call'
	from /home/rails/lib/redis.rb:89:in `block in ping'
	from /home/rails/lib/redis.rb:37:in `block in synchronize'
	from /home/rails/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /home/rails/lib/redis.rb:37:in `synchronize'
	from /home/rails/lib/redis.rb:88:in `ping'
	from test.rb:28:in `<main>'

**Comment by badboy** [comment]
According to your config you're _monitoring_ `127.0.0.1:26379`, so your actual Sentinel instance isn't running on that port. But you still pass it as a Sentinel node to redis-rb, which then of course fails to actually ask a Sentinel for the right master.

You must give atleast one Sentinel instance in the `:sentinels` array.

**Comment by ArunSakthivel** [comment]
I have ran below command in console, I have checked the Sentinel process is running.
````
netstat -anp |grep 26379
````
![redis_server_sentinetal](https://cloud.githubusercontent.com/assets/6821906/8030997/d4673bc4-0de8-11e5-94eb-964eca270664.png)

**Comment by badboy** [comment]
I don't know your setup, but you should. Figure out which one's are real Redis instances and which are Sentinel instances. Keep in mind normal Redis is _different_ from Sentinel and you need Sentinel to monitor normal Redis. If you need further help join the IRC channel, where you might get faster help :)

**Comment by ArunSakthivel** [comment]
Check the below image for Sentinel redis start
```
redis-server sentinel.conf --sentinel
````
![redis_server_start](https://cloud.githubusercontent.com/assets/6821906/8031260/966f09bc-0dea-11e5-8433-146a56bfd714.png)


Apart from this, I missed anything?
