### ISSUE TITLE
Cannot connect to server by external IP (even on same server)

### ISSUE THREAD

**Issue by Phrogz** [redis/redis-rb#574]
This works:

```ruby
require 'redis'
Redis.new(host:'127.0.0.1').set('foo',42)
```

This fails (where the IP in question is the same machine):

```ruby
require 'redis'
Redis.new(host:'10.20.117.104').set('foo',42)
#=> Redis::CannotConnectError: Error connecting to Redis on 10.20.118.104:6379 (Errno::ECONNREFUSED)
#=>         from /var/lib/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:332:in `rescue in establish_connection'
#=>         from /var/lib/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:318:in `establish_connection'
#=>         from /var/lib/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:94:in `block in connect'
#=>         from /var/lib/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:280:in `with_reconnect'
#=>         from /var/lib/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:93:in `connect'
#=>         from /var/lib/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:351:in `ensure_connected'
#=>         from /var/lib/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:208:in `block in process'
#=>         from /var/lib/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:293:in `logging'
#=>         from /var/lib/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:207:in `process'
#=>         from /var/lib/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:113:in `call'
#=>         from /var/lib/gems/2.1.0/gems/redis-3.2.2/lib/redis.rb:714:in `block in set'
#=>         from /var/lib/gems/2.1.0/gems/redis-3.2.2/lib/redis.rb:57:in `block in synchronize'
#=>         from /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
#=>         from /var/lib/gems/2.1.0/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'
#=>         from /var/lib/gems/2.1.0/gems/redis-3.2.2/lib/redis.rb:710:in `set'
```

**Comment by badboy** [comment]
That is not an issue with redis-rb.
You probably just configured Redis to only listen on 127.0.0.1 only.

**Comment by Phrogz** [comment]
FWIW you are correct. I actually had a redis server instance running (that I did not know about) and when I started a second server it bound the same port to a different IP mask. (!) Running exactly one Redis server fixed the issue.
