### ISSUE TITLE
sidekiq can't run NOAUTH

### ISSUE THREAD

**Issue by pevargasg** [redis/redis-rb#583]
Hi, I'm trying to run sidekiq in my computer and I can perfectly run redis, but when I try to run sidekiq i get this error..
2016-01-18T20:56:01.091Z 2997 TID-grscb4it0 INFO: Running in ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
2016-01-18T20:56:01.091Z 2997 TID-grscb4it0 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2016-01-18T20:56:01.091Z 2997 TID-grscb4it0 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2016-01-18T20:56:01.091Z 2997 TID-grscb4it0 INFO: Booting Sidekiq 4.0.1 with redis options {:url=>nil}
NOAUTH Authentication required.
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:114:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis.rb:211:in `block in info'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis.rb:57:in `block in synchronize'
/usr/local/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis.rb:210:in `info'
/usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/cli.rb:71:in `block in run'
/usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq.rb:84:in `block in redis'
/usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
/usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
/usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
/usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
/usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
/usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq.rb:81:in `redis'
/usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/cli.rb:68:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/bin/sidekiq:13:in `<top (required)>'
/usr/local/bin/sidekiq:23:in `load'
/usr/local/bin/sidekiq:23:in `<main>'

I have tried to set the requirepass in the redis.conf file and made a redis file initializer in my rails project but non of this work

**Comment by badboy** [comment]
It's telling you that it can't execute commands because it is not authorized. So either you did not set a password in Sidekiq's configuration or you set the wrong one.

Either way, this is not a problem with the client lib, but with your configuration.

**Comment by pevargasg** [comment]
@badboy how can I set a password in Sidekiq?

**Comment by badboy** [comment]
Set it in the redis URL: https://github.com/mperham/sidekiq/wiki/Using-Redis

**Comment by pevargasg** [comment]
@badboy so I tried that and it didn't work then I tried Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://127.0.0.1:6379',password:'Policia9'}
end

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://127.0.0.1:6379',password:'Policia9'}
end
 and when a run it , thousands of this errors appear 
016-01-19T00:41:48.194Z 14000 TID-gn0us7zl0 ERROR: /usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:85:in `get_one'
2016-01-19T00:41:48.194Z 14000 TID-gn0us7fgk ERROR: /usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
2016-01-19T00:41:48.194Z 14000 TID-gn0us7zl0 ERROR: /usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:95:in `fetch'
2016-01-19T00:41:48.194Z 14000 TID-gn0us7fgk ERROR: /usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq.rb:81:in `redis'
2016-01-19T00:41:48.194Z 14000 TID-gn0us7zl0 ERROR: /usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:78:in `process_one'
2016-01-19T00:41:48.194Z 14000 TID-gn0us7fgk ERROR: /usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/fetch.rb:35:in `retrieve_work'
2016-01-19T00:41:48.194Z 14000 TID-gn0us7zl0 ERROR: /usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run'
2016-01-19T00:41:48.194Z 14000 TID-gn0us7fgk ERROR: /usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:85:in `get_one'
2016-01-19T00:41:48.194Z 14000 TID-gn0us7zl0 ERROR: /usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
2016-01-19T00:41:48.194Z 14000 TID-gn0us7fgk ERROR: /usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:95:in `fetch'
2016-01-19T00:41:48.194Z 14000 TID-gn0us7zl0 ERROR: /usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
2016-01-19T00:41:48.194Z 14000 TID-gn0us7fgk ERROR: /usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:78:in `process_one'
2016-01-19T00:41:48.194Z 14000 TID-gn0us7fgk ERROR: /usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run'
2016-01-19T00:41:48.194Z 14000 TID-gn0us7fgk ERROR: /usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog'
2016-01-19T00:41:48.194Z 14000 TID-gn0us7fgk ERROR: /usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
^C2016-01-19T00:41:48.219Z 14000 TID-gn0u3lq9c INFO: Shutting down
2016-01-19T00:41:48.219Z 14000 TID-gn0u3lq9c INFO: Terminating quiet workers
2016-01-19T00:41:48.219Z 14000 TID-gn0unaybs INFO: Scheduler exiting...
2016-01-19T00:41:48.720Z 14000 TID-gn0u3lq9c INFO: Pausing to allow workers to finish...
2016-01-19T00:41:49.221Z 14000 TID-gn0u3lq9c INFO: Bye!

**Comment by pevargasg** [comment]
@badboy Also if i try this Sidekiq.configure_server do |config|
  config.redis = { url: 'redis://redis.example.com:6379/12',password:'Policia9'}
end

Sidekiq.configure_client do |config|
  config.redis = { url: 'redis://redis.example.com:6379/12',password:'Policia9'}
end

 i get this error 
2016-01-19T00:44:05.574Z 16683 TID-gqy8usdv4 INFO: Running in ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
2016-01-19T00:44:05.574Z 16683 TID-gqy8usdv4 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2016-01-19T00:44:05.574Z 16683 TID-gqy8usdv4 INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
getaddrinfo: Name or service not known
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis/connection/ruby.rb:152:in `getaddrinfo'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis/connection/ruby.rb:152:in `connect'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis/connection/ruby.rb:211:in `connect'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:323:in `establish_connection'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:94:in `block in connect'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:280:in `with_reconnect'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:93:in `connect'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:351:in `ensure_connected'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:208:in `block in process'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:293:in `logging'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:207:in `process'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis/client.rb:113:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis.rb:211:in `block in info'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis.rb:57:in `block in synchronize'
/usr/local/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'
/usr/local/lib/ruby/gems/2.1.0/gems/redis-3.2.2/lib/redis.rb:210:in `info'
/usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/cli.rb:71:in `block in run'
/usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq.rb:84:in `block in redis'
/usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
/usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
/usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
/usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
/usr/local/lib/ruby/gems/2.1.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
/usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq.rb:81:in `redis'
/usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/lib/sidekiq/cli.rb:68:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/sidekiq-4.0.1/bin/sidekiq:13:in `<top (required)>'
/usr/local/bin/sidekiq:23:in `load'
/usr/local/bin/sidekiq:23:in `<main>'

**Comment by badboy** [comment]
The syntax would be `redis://:password@host:port`.
The error message above already tells you quite a bit: `Name or service not known`. Seems you simply used the non-existent host given in the docu, of course you need to put your own host or ip in there.

Keep in mind this is not a Sidekiq support forum. You should use their documentation and support channels to get help with the configuration (tip: this question was answered on StackOverflow already at least twice)
