### ISSUE TITLE
Redis::ConnectionError: Connection lost (ECONNRESET) (3.2.2)

### ISSUE THREAD

**Issue by Lavode** [redis/redis-rb#589]
Hello,

We are running Logstash (data pipeline), with some of the inputs/outputs being a local Redis server, which Logstash connects to with this gem.
A few seconds after connecting, it then starts spewing out ConnectionErrors. (See below for the full stacktrace).

Redis is complaining about a protocol error - its debugging output is listed further down, too.

Could this be something on your side?

```
Logstash error message, containing redis gem stacktrace:
{:timestamp=>"2016-02-29T12:39:02.337000+0000", :message=>"Failed to send backlog of events to Redis", :identity=>"default", :exception=>#<Redis::ConnectionError: Connection lost (ECONNRESET)>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.2.2/lib/redis/client.rb:244:in `io'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.2.2/lib/redis/client.rb:237:in `io'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.2.2/lib/redis/client.rb:256:in `write'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.2.2/lib/redis/client.rb:215:in `process'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.2.2/lib/redis/client.rb:209:in `process'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.2.2/lib/redis/client.rb:354:in `ensure_connected'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.2.2/lib/redis/client.rb:208:in `process'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.2.2/lib/redis/client.rb:293:in `logging'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.2.2/lib/redis/client.rb:207:in `process'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.2.2/lib/redis/client.rb:113:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.2.2/lib/redis.rb:1030:in `rpush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'", "/opt/logstash/vendor/jruby/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'", "/opt/logstash/vendor/jruby/lib/ruby/1.9/monitor.rb:210:in `mon_synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.2.2/lib/redis.rb:57:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.2.2/lib/redis.rb:1029:in `rpush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-redis-1.0.0/lib/logstash/outputs/redis.rb:200:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:221:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:159:in `buffer_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-redis-1.0.0/lib/logstash/outputs/redis.rb:147:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.6-java/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):285:in `output_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.6-java/lib/logstash/pipeline.rb:244:in `outputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.6-java/lib/logstash/pipeline.rb:166:in `start_outputs'"], :level=>:warn}
```

```
Redis server debugging output:
5791:M 29 Feb 12:42:08.898 - Accepted 127.0.0.1:57426
5791:M 29 Feb 12:42:09.517 - Protocol error from client: id=654 addr=127.0.0.1:57426 fd=5 name= age=1 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=16384 qbuf-free=16384 obl=42 oll=0 omem=0 events=rw cmd=NULL
5791:M 29 Feb 12:42:09.538 - DB 0: 2 keys (0 volatile) in 4 slots HT.
5791:M 29 Feb 12:42:09.538 - 0 clients connected (0 slaves), 2075778960 bytes in use
5791:M 29 Feb 12:42:10.643 - Accepted 127.0.0.1:57427
5791:M 29 Feb 12:42:10.963 - Protocol error from client: id=655 addr=127.0.0.1:57427 fd=5 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=16384 qbuf-free=16384 obl=42 oll=0 omem=0 events=rw cmd=llen
5791:M 29 Feb 12:42:11.084 - Accepted 127.0.0.1:57428
5791:M 29 Feb 12:42:11.735 - Protocol error from client: id=656 addr=127.0.0.1:57428 fd=5 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=16384 qbuf-free=16384 obl=42 oll=0 omem=0 events=rw cmd=NULL
```

```
Use software:
Redis gem: 3.2.2

Redis: Redis server v=3.0.5 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=1e97dc538215b523

Logstash: 1.5.6

JRuby: jruby 1.7.23 (1.9.3p551) 2015-11-24 f496dd5 on OpenJDK 64-Bit Server VM 1.7.0_79-b14 +jit [linux-amd64]

OS: 
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.2 (jessie)
Release:	8.2
Codename:	jessie
```

**Comment by badboy** [comment]
```
5791:M 29 Feb 12:42:09.517 - Protocol error from client:
```

Somewhere you send an invalid string, that does not conform to the Redis protocol. Without any code we can't see what's causing this.

**Comment by Lavode** [comment]
Thanks for the info, in this case I'll ask the Logstash guys about this. :)

**Comment by NafaaBout** [comment]
I'd like to reopen this issue because I encountered this same error many times this last week. The problem happen when I use `hmset` with a big number of fields. The problem is that this same error is raised even on my local machine, but it's worse when Redis is on a remote server.
