### ISSUE TITLE
RuntimeError: System Error

### ISSUE THREAD

**Issue by hendricius** [redis/redis-rb#629]
When I am performing heavy operations I sometimes get a `RuntimeError: System Error`. However I am not sure why this is happening. I am using `3.3.0` version of the gem. The line that seems to cause this error is here: https://github.com/redis/redis-rb/blob/master/lib/redis/connection/hiredis.rb#L19. Has anyone had something similar before?

![image](https://cloud.githubusercontent.com/assets/816859/17293941/adbf640a-57f3-11e6-99bb-c871832298f0.png)

Or here as text:

```
2016-08-01T08:23:47.798Z 23177 TID-or3mjsemg WARN: {"class"=>"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper", "wrapped"=>"SimilarUsers::ScheduleUserIdsJob", "queue"=>"similar_users", "args"=>[{"job_class"=>"SimilarUsers::ScheduleUserIdsJob", "job_id"=>"afd39622-9b12-4347-abf1-c7db53eef323", "queue_name"=>"simi
lar_users", "arguments"=>[[107778, 107779, 107780, 107781, 107782]], "locale"=>"en"}], "retry"=>true, "jid"=>"34644857c4f6bb6f9aa749b3", "created_at"=>1470039675.701064, "bid"=>"2LzdxtY-QlvZ2Q", "enqueued_at"=>1470039675.701306, "error_message"=>"System error", "error_class"=>"RuntimeError", "failed_at"=>1470039827.7
947474, "retry_count"=>0, "processor"=>"ip-172-31-23-206:23177"}
2016-08-01T08:23:47.798Z 23177 TID-or3mjsemg WARN: RuntimeError: System error
2016-08-01T08:23:47.798Z 23177 TID-or3mjsemg WARN: /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/connection/hiredis.rb:19:in `connect'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/connection/hiredis.rb:19:in `connect'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:336:in `establish_connection'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:101:in `block in connect'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:293:in `with_reconnect'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:100:in `connect'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:364:in `ensure_connected'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:221:in `block in process'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:306:in `logging'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:220:in `process'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:187:in `call_pipelined'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:157:in `block in call_pipeline'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:293:in `with_reconnect'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:155:in `call_pipeline'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis.rb:2253:in `block in pipelined'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis.rb:58:in `block in synchronize'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis.rb:58:in `synchronize'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis.rb:2249:in `pipelined'
/home/ubuntu/tripl/app/features/similar_users/data_prepare.rb:6:in `push_data_to_redis'
/home/ubuntu/tripl/app/features/similar_users/schedule_user_ids_job.rb:13:in `schedule_for_user'
/home/ubuntu/tripl/app/features/similar_users/schedule_user_ids_job.rb:8:in `block in perform'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
/home/ubuntu/tripl/app/features/similar_users/schedule_user_ids_job.rb:7:in `perform'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activejob-4.2.6/lib/active_job/execution.rb:32:in `block in perform_now'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:343:in `call'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/active_job.rb:46:in `call'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/active_job.rb:46:in `perform'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/active_job.rb:20:in `block (3 levels) in <top (required)>'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:441:in `instance_exec'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:342:in `call'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:342:in `block in simple'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:497:in `call'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:497:in `block in around'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
```

We are using ElasticCache by AWS. That is running on Redis 2.8.

**Comment by badboy** [comment]
Please post the full stack trace as text, not as an image

**Comment by hendricius** [comment]
Yep. Sorry.

```
2016-08-01T08:23:47.798Z 23177 TID-or3mjsemg WARN: {"class"=>"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper", "wrapped"=>"SimilarUsers::ScheduleUserIdsJob", "queue"=>"similar_users", "args"=>[{"job_class"=>"SimilarUsers::ScheduleUserIdsJob", "job_id"=>"afd39622-9b12-4347-abf1-c7db53eef323", "queue_name"=>"simi
lar_users", "arguments"=>[[107778, 107779, 107780, 107781, 107782]], "locale"=>"en"}], "retry"=>true, "jid"=>"34644857c4f6bb6f9aa749b3", "created_at"=>1470039675.701064, "bid"=>"2LzdxtY-QlvZ2Q", "enqueued_at"=>1470039675.701306, "error_message"=>"System error", "error_class"=>"RuntimeError", "failed_at"=>1470039827.7
947474, "retry_count"=>0, "processor"=>"ip-172-31-23-206:23177"}
2016-08-01T08:23:47.798Z 23177 TID-or3mjsemg WARN: RuntimeError: System error
2016-08-01T08:23:47.798Z 23177 TID-or3mjsemg WARN: /home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/connection/hiredis.rb:19:in `connect'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/connection/hiredis.rb:19:in `connect'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:336:in `establish_connection'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:101:in `block in connect'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:293:in `with_reconnect'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:100:in `connect'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:364:in `ensure_connected'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:221:in `block in process'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:306:in `logging'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:220:in `process'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:187:in `call_pipelined'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:157:in `block in call_pipeline'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:293:in `with_reconnect'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis/client.rb:155:in `call_pipeline'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis.rb:2253:in `block in pipelined'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis.rb:58:in `block in synchronize'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis.rb:58:in `synchronize'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.3.0/lib/redis.rb:2249:in `pipelined'
/home/ubuntu/tripl/app/features/similar_users/data_prepare.rb:6:in `push_data_to_redis'
/home/ubuntu/tripl/app/features/similar_users/schedule_user_ids_job.rb:13:in `schedule_for_user'
/home/ubuntu/tripl/app/features/similar_users/schedule_user_ids_job.rb:8:in `block in perform'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
/home/ubuntu/tripl/app/features/similar_users/schedule_user_ids_job.rb:7:in `perform'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activejob-4.2.6/lib/active_job/execution.rb:32:in `block in perform_now'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:343:in `call'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/active_job.rb:46:in `call'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/active_job.rb:46:in `perform'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/active_job.rb:20:in `block (3 levels) in <top (required)>'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:441:in `instance_exec'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:342:in `call'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:342:in `block in simple'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:497:in `call'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:497:in `block in around'
/home/ubuntu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
```

**Comment by badboy** [comment]
Hm, I never saw that error before and it is really not that meaningful. I don't know how to debug this.

**Comment by hendricius** [comment]
Yep - same issue here. It seems to be something temporary. When the job restarts, the error is gone and won't happen again.

**Comment by byroot** [comment]
This issue is stale and not really actionable. Feel free to reopen if you have more info.
