### ISSUE TITLE
Release 3.3.3 still create timeouts, 3.3.1 is good

### ISSUE THREAD

**Issue by le0pard** [redis/redis-rb#685]
Hello.

Issue, which was with 3.3.2 still present in 3.3.3 - "Errno::ETIMEDOUT: Connection timed out"

I made upgrade from 3.3.1 to 3.3.3 (after this [comment](https://github.com/redis/redis-rb/issues/650#issuecomment-274554878)) and after this begin such errors:

```
Errno::ETIMEDOUT: Connection timed out
  from redis/connection/hiredis.rb:19:in `connect'
  from redis/connection/hiredis.rb:19:in `connect'
  from redis/client.rb:336:in `establish_connection'
  from redis/client.rb:101:in `block in connect'
  from redis/client.rb:293:in `with_reconnect'
  from redis/client.rb:100:in `connect'
  from new_relic/agent/instrumentation/redis.rb:105:in `connect'
  from redis/client.rb:364:in `ensure_connected'
  from redis/client.rb:221:in `block in process'
  from redis/client.rb:306:in `logging'
  from redis/client.rb:220:in `process'
  from redis/client.rb:120:in `call'
  from new_relic/agent/instrumentation/redis.rb:69:in `call'
  from redis.rb:862:in `block in get'
  from redis.rb:58:in `block in synchronize'
  from monitor.rb:214:in `mon_synchronize'
  from redis.rb:58:in `synchronize'
  from redis.rb:861:in `get'
  from redis/store/interface.rb:5:in `get'
  from redis/store/marshalling.rb:17:in `get'
  from redis/store/namespace.rb:23:in `block in get'
  from redis/store/namespace.rb:84:in `namespace'
  from redis/store/namespace.rb:23:in `get'
  from rack/session/redis.rb:50:in `block (2 levels) in get_session'
  from rack/session/redis.rb:90:in `with'
  from rack/session/redis.rb:50:in `block in get_session'
  from rack/session/redis.rb:75:in `with_lock'
  from rack/session/redis.rb:49:in `get_session'
  from rack/session/abstract/id.rb:415:in `find_session'
  from rack/session/abstract/id.rb:270:in `load_session'
  from action_dispatch/middleware/session/abstract_store.rb:56:in `block in load_session'
  from action_dispatch/middleware/session/abstract_store.rb:64:in `stale_session_check!'
  from action_dispatch/middleware/session/abstract_store.rb:56:in `load_session'
  from action_dispatch/request/session.rb:216:in `load!'
  from action_dispatch/request/session.rb:208:in `load_for_read!'
  from action_dispatch/request/session.rb:90:in `[]'
  from warden/session_serializer.rb:31:in `fetch'
  from warden/proxy.rb:213:in `user'
  from warden/proxy.rb:323:in `_perform_authentication'
  from warden/proxy.rb:128:in `authenticate!'
  from devise/controllers/helpers.rb:116:in `authenticate_user!'
  from active_support/callbacks.rb:382:in `block in make_lambda'
  from active_support/callbacks.rb:150:in `block (2 levels) in halting_and_conditional'
  from abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
  from active_support/callbacks.rb:151:in `block in halting_and_conditional'
  from active_support/callbacks.rb:454:in `block in call'
  from active_support/callbacks.rb:454:in `each'
  from active_support/callbacks.rb:454:in `call'
  from active_support/callbacks.rb:101:in `__run_callbacks__'
  from active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  from active_support/callbacks.rb:90:in `run_callbacks'
  from abstract_controller/callbacks.rb:19:in `process_action'
  from action_controller/metal/instrumentation.rb:32:in `block in process_action'
  from active_support/notifications.rb:164:in `block in instrument'
...
Redis::TimeoutError: Redis::TimeoutError
  from redis/connection/hiredis.rb:26:in `rescue in connect'
  from redis/connection/hiredis.rb:11:in `connect'
  from redis/client.rb:336:in `establish_connection'
  from redis/client.rb:101:in `block in connect'
  from redis/client.rb:293:in `with_reconnect'
  from redis/client.rb:100:in `connect'
  from new_relic/agent/instrumentation/redis.rb:105:in `connect'
  from redis/client.rb:364:in `ensure_connected'
  from redis/client.rb:221:in `block in process'
  from redis/client.rb:306:in `logging'
  from redis/client.rb:220:in `process'
  from redis/client.rb:120:in `call'
  from new_relic/agent/instrumentation/redis.rb:69:in `call'
  from redis.rb:862:in `block in get'
  from redis.rb:58:in `block in synchronize'
  from monitor.rb:214:in `mon_synchronize'
  from redis.rb:58:in `synchronize'
  from redis.rb:861:in `get'
  from redis/store/interface.rb:5:in `get'
  from redis/store/marshalling.rb:17:in `get'
  from redis/store/namespace.rb:23:in `block in get'
  from redis/store/namespace.rb:84:in `namespace'
  from redis/store/namespace.rb:23:in `get'
  from rack/session/redis.rb:50:in `block (2 levels) in get_session'
  from rack/session/redis.rb:90:in `with'
  from rack/session/redis.rb:50:in `block in get_session'
  from rack/session/redis.rb:75:in `with_lock'
  from rack/session/redis.rb:49:in `get_session'
  from rack/session/abstract/id.rb:415:in `find_session'
  from rack/session/abstract/id.rb:270:in `load_session'
  from action_dispatch/middleware/session/abstract_store.rb:56:in `block in load_session'
  from action_dispatch/middleware/session/abstract_store.rb:64:in `stale_session_check!'
  from action_dispatch/middleware/session/abstract_store.rb:56:in `load_session'
  from action_dispatch/request/session.rb:216:in `load!'
  from action_dispatch/request/session.rb:208:in `load_for_read!'
  from action_dispatch/request/session.rb:90:in `[]'
  from warden/session_serializer.rb:31:in `fetch'
  from warden/proxy.rb:213:in `user'
  from warden/proxy.rb:323:in `_perform_authentication'
  from warden/proxy.rb:128:in `authenticate!'
```

and from different places:

```
Errno::ETIMEDOUT: Connection timed out
  from redis/connection/hiredis.rb:19:in `connect'
  from redis/connection/hiredis.rb:19:in `connect'
  from redis/client.rb:336:in `establish_connection'
  from redis/client.rb:101:in `block in connect'
  from redis/client.rb:293:in `with_reconnect'
  from redis/client.rb:100:in `connect'
  from new_relic/agent/instrumentation/redis.rb:105:in `connect'
  from redis/client.rb:364:in `ensure_connected'
  from redis/client.rb:221:in `block in process'
  from redis/client.rb:306:in `logging'
  from redis/client.rb:220:in `process'
  from redis/client.rb:120:in `call'
  from new_relic/agent/instrumentation/redis.rb:69:in `call'
  from redis.rb:880:in `block in mget'
  from redis.rb:58:in `block in synchronize'
  from monitor.rb:214:in `mon_synchronize'
  from redis.rb:58:in `synchronize'
  from redis.rb:879:in `mget'
  from redis/store/marshalling.rb:22:in `mget'
  from redis/store/namespace.rb:51:in `mget'
  from active_support/cache/redis_store.rb:98:in `block in read_multi'
  from connection_pool.rb:64:in `block (2 levels) in with'
  from connection_pool.rb:63:in `handle_interrupt'
  from connection_pool.rb:63:in `block in with'
  from connection_pool.rb:60:in `handle_interrupt'
  from connection_pool.rb:60:in `with'
  from active_support/cache/redis_store.rb:218:in `with'
  from active_support/cache/redis_store.rb:98:in `read_multi'
  from config/initializers/rabl.rb:27:in `read_multi'
  from rabl/multi_builder.rb:87:in `read_cache_results'
  from rabl/multi_builder.rb:23:in `to_a'
  from rabl/engine.rb:88:in `to_hash'
  from rabl/engine.rb:99:in `to_dumpable'
  from rabl/engine.rb:108:in `to_json'
  from rabl/engine.rb:48:in `block in render'
  from rabl/engine.rb:380:in `cache_results'
  from rabl/engine.rb:47:in `render'

```

Ruby: 2.4.1
Gems:

 * rails (5.0.2)
 * redis (3.3.3)
 * hiredis (0.6.1)

As I wrote, after downgrade to 3.3.1 all back to normal. On redis server "timeout 0".

Thanks.

**Comment by le0pard** [comment]
Maybe it some network distruption, get first error from 3.3.1. Continue monitoring.

**Comment by jdurand** [comment]
It seems there's a regression on this in v3.3.5. I just reverted to 3.3.3 and I don't get this error.
