### ISSUE TITLE
Redis gem crashes app on heroku

### ISSUE THREAD

**Issue by neycodes** [redis/redis-rb#726]
I set up Redis a few months ago and deployed my app to heroku. I ran my app and it all worked fine.

Now the redis gem crashes the app whenever the app is opened.

This is what I get in the heroku logs:

```
2017-10-24T20:22:44.271431+00:00 heroku[worker.1]: Starting process with command `bundle exec sidekiq -C config/sidekiq.yml`
2017-10-24T20:22:44.844756+00:00 heroku[worker.1]: State changed from starting to up
2017-10-24T20:22:45.642440+00:00 heroku[web.1]: Starting process with command `bundle exec puma -C config/puma.rb`
2017-10-24T20:22:49.340657+00:00 app[worker.1]: 4 TID-4rgmg INFO: Running in ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
2017-10-24T20:22:49.340670+00:00 app[worker.1]: 4 TID-4rgmg INFO: See LICENSE and the LGPL-3.0 for licensing details.
2017-10-24T20:22:49.340700+00:00 app[worker.1]: 4 TID-4rgmg INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
2017-10-24T20:22:49.340906+00:00 app[worker.1]: 4 TID-4rgmg INFO: Booting Sidekiq 5.0.0 with redis options {:url=>"redis://rediscloud:REDACTED@redis-16426.c15.us-east-1-2.ec2.cloud.redislabs.com:16426"}
2017-10-24T20:22:49.353839+00:00 app[worker.1]: getaddrinfo: Name or service not known
2017-10-24T20:22:49.353846+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/connection/ruby.rb:229:in `getaddrinfo'
2017-10-24T20:22:49.353847+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/connection/ruby.rb:229:in `connect'
2017-10-24T20:22:49.353848+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/connection/ruby.rb:313:in `connect'
2017-10-24T20:22:49.353849+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:336:in `establish_connection'
2017-10-24T20:22:49.353849+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:101:in `block in connect'
2017-10-24T20:22:49.353850+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:293:in `with_reconnect'
2017-10-24T20:22:49.353851+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:100:in `connect'
2017-10-24T20:22:49.353851+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:364:in `ensure_connected'
2017-10-24T20:22:49.353852+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:221:in `block in process'
2017-10-24T20:22:49.353853+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:306:in `logging'
2017-10-24T20:22:49.353854+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:220:in `process'
2017-10-24T20:22:49.353854+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/client.rb:120:in `call'
2017-10-24T20:22:49.353855+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis.rb:251:in `block in info'
2017-10-24T20:22:49.353856+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
2017-10-24T20:22:49.353856+00:00 app[worker.1]: /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
2017-10-24T20:22:49.353857+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
2017-10-24T20:22:49.353858+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis.rb:250:in `info'
2017-10-24T20:22:49.353858+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.0/lib/sidekiq.rb:113:in `block in redis_info'
2017-10-24T20:22:49.353859+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.0/lib/sidekiq.rb:95:in `block in redis'
2017-10-24T20:22:49.353860+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
2017-10-24T20:22:49.353861+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
2017-10-24T20:22:49.353861+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
2017-10-24T20:22:49.353862+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
2017-10-24T20:22:49.353863+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
2017-10-24T20:22:49.353863+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.0/lib/sidekiq.rb:92:in `redis'
2017-10-24T20:22:49.353864+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.0/lib/sidekiq.rb:106:in `redis_info'
2017-10-24T20:22:49.353865+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.0/lib/sidekiq/cli.rb:81:in `run'
2017-10-24T20:22:49.353865+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/sidekiq-5.0.0/bin/sidekiq:12:in `<top (required)>'
2017-10-24T20:22:49.353866+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/bin/sidekiq:22:in `load'
2017-10-24T20:22:49.353866+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/bin/sidekiq:22:in `<top (required)>'
2017-10-24T20:22:49.353867+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
2017-10-24T20:22:49.353868+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
2017-10-24T20:22:49.353868+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
2017-10-24T20:22:49.353869+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
2017-10-24T20:22:49.353869+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2017-10-24T20:22:49.353870+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
2017-10-24T20:22:49.353870+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
2017-10-24T20:22:49.353871+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
2017-10-24T20:22:49.353872+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
2017-10-24T20:22:49.353872+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
2017-10-24T20:22:49.353873+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
2017-10-24T20:22:49.353873+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
2017-10-24T20:22:49.353874+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
2017-10-24T20:22:49.353875+00:00 app[worker.1]: /app/bin/bundle:3:in `load'
2017-10-24T20:22:49.353875+00:00 app[worker.1]: /app/bin/bundle:3:in `<main>'
2017-10-24T20:22:49.518342+00:00 heroku[worker.1]: Process exited with status 1
2017-10-24T20:22:49.526304+00:00 heroku[worker.1]: State changed from up to crashed
```

I've been trying to figure out why this is happening now when it was working fine before, and I haven't made any changes since I set up Redis. I am using Redis Cloud on heroku.

Redis gem version is 3.3.3

**Comment by badboy** [comment]
```
getaddrinfo: Name or service not known
```

It can't resolve the given hostname. The one in the logs does not exist.
