### ISSUE TITLE
ConnectionError while acccessing AWS ElastiCache

### ISSUE THREAD

**Issue by santhoshcd** [redis/redis-rb#729]
Hi
We are migrating cache server from Redis to AWS ElastiCache and getting connection error while connecting to the AWS ElastiCache service.

Details
Ruby Version : 1.8.7
Rails Version: 2.3.2
redis : 3.2.1
```
=>redis =Redis.new( :host=>"xxx.abc.xxx.xxx.cache.amazonaws.com",
:password => "password",
:port => 6379)
#<Redis client v3.2.1 for redis://xxx.abc.xxx.xxx.cache.amazonaws.com:6379/0>

=>redis.set("key","value")
Redis::ConnectionError: Connection lost (ECONNRESET)
        from /home/navigator/.rvm/gems/ruby-1.8.7-p358/gems/redis-3.2.1/lib/redis/client.rb:243:in `io'
        from /home/navigator/.rvm/gems/ruby-1.8.7-p358/gems/redis-3.2.1/lib/redis/client.rb:247:in `read'
        from /home/navigator/.rvm/gems/ruby-1.8.7-p358/gems/redis-3.2.1/lib/redis/client.rb:112:in `call'
        from /home/navigator/.rvm/gems/ruby-1.8.7-p358/gems/redis-3.2.1/lib/redis/client.rb:217:in `process'
        from /home/navigator/.rvm/gems/ruby-1.8.7-p358/gems/redis-3.2.1/lib/redis/client.rb:353:in `ensure_connected'
```

Please help me to solve this problem.

**Comment by badboy** [comment]
`ECONNRESET` => Looks like your upstream server does not allow you to connect.
We can't help with application issues.
