### ISSUE TITLE
private method `timeout' called for #<Redis::Pipeline::Multi:0x00007ff3efbd0728> (NoMethodError)

### ISSUE THREAD

**Issue by linkyndy** [redis/redis-rb#753]
I have the following bit of code:

```
client.multi do |multi|
  multi.brpoplpush(from, to, timeout: 10)
  [...]
end
```

If I execute it, I get:

```
private method `timeout' called for #<Redis::Pipeline::Multi:0x00007ff3efbd0728> (NoMethodError)
/Users/abc/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/redis-4.0.1/lib/redis.rb:1229:in `block in brpoplpush'
/Users/abc/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
/Users/abc/.rbenv/versions/2.4.3/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/abc/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
/Users/abc/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/redis-4.0.1/lib/redis.rb:1227:in `brpoplpush'
/Users/abc/GitHub/pallets/lib/pallets/backends/redis.rb:20:in `block (2 levels) in pick_work'
/Users/abc/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/redis-4.0.1/lib/redis.rb:2352:in `block in multi'
/Users/abc/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
/Users/abc/.rbenv/versions/2.4.3/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/abc/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
/Users/abc/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/redis-4.0.1/lib/redis.rb:2345:in `multi'
[...]
```

I am running redis `4.0.1` on ruby `2.4.3`.

Am I doing something wrong? I find this error weird, since the [manual](https://redis.io/commands/brpoplpush) hints that `BRPOPLPUSH` should work inside a `MULTI/EXEC` block.

**Comment by byroot** [comment]
> ince the [manual](https://redis.io/commands/brpoplpush) hints that `BRPOPLPUSH` should work inside a `MULTI/EXEC` block.

I wasn't sure how to handle a specific command timeout, inside a pipeline, but according to the documentation:

```
When used inside a MULTI/EXEC block, this command behaves exactly like RPOPLPUSH. 
```

So basically it should just be ignored. I'll try to implement it that way.
