### ISSUE TITLE
Redis::ConnectionError: Connection lost (ECONNRESET) when using ElastiCache with TLS enabled

### ISSUE THREAD

**Issue by k-rudy** [redis/redis-rb#771]
Hey guys,

Amazon ElastiCache allows to set `encrypt in-transit = true` for Redis cluster, which enables TLS, but seems like `redis.rb` cannot handle it:

```ruby
irb(main):006:0> Redis.new(url: 'redis://master....cache.amazonaws.com:6379').get('some_key')
Redis::ConnectionError: Connection lost (ECONNRESET)
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:255:in `rescue in io'
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:248:in `io'
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:259:in `read'
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:118:in `block in call'
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:229:in `block (2 levels) in process'
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:366:in `ensure_connected'
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:219:in `block in process'
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:304:in `logging'
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:218:in `process'
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/redis-4.0.1/lib/redis/client.rb:118:in `call'
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:889:in `block in get'
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
	from /usr/lib64/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/redis-4.0.1/lib/redis.rb:888:in `get'
	from (irb):6
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/railties-5.0.5/lib/rails/commands/console.rb:65:in `start'
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/railties-5.0.5/lib/rails/commands/console_helper.rb:9:in `start'
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/railties-5.0.5/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/railties-5.0.5/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /data/api/shared/bundled_gems/ruby/2.3.0/gems/railties-5.0.5/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

Is there any option in `redis.rb` to enable TLS support?

**Comment by tubbo** [comment]
I didn't notice this when you posted in redis-store, but did you try using `rediss://` as the URI schema?

**Comment by k-rudy** [comment]
works with `rediss` like a charm. Thank you guys

**Comment by tubbo** [comment]
haha sorry about making you create an issue twice, but now at least when people search GH issues they'll find this discussion :)
