### ISSUE TITLE
Rounding errors in test suite

### ISSUE THREAD

**Issue by voxik** [redis/redis-rb#777]
I occasionally observe test suite failures such as:

~~~
Failure: test_hincrbyfloat(TestCommandsOnHashes)
/builddir/build/BUILD/rubygem-redis-4.0.1/usr/share/gems/gems/redis-4.0.1/test/lint/hashes.rb:150:in `block in test_hincrbyfloat'
     147:       target_version "2.5.4" do
     148:         r.hincrbyfloat("foo", "f1", 1.23)
     149: 
  => 150:         assert_equal "1.23", r.hget("foo", "f1")
     151: 
     152:         r.hincrbyfloat("foo", "f1", 0.77)
     153: 
/builddir/build/BUILD/rubygem-redis-4.0.1/usr/share/gems/gems/redis-4.0.1/test/helper.rb:156:in `target_version'
/builddir/build/BUILD/rubygem-redis-4.0.1/usr/share/gems/gems/redis-4.0.1/test/lint/hashes.rb:147:in `test_hincrbyfloat'
/builddir/build/BUILD/rubygem-redis-4.0.1/usr/share/gems/gems/redis-4.0.1/test/helper.rb:60:in `run'
<"1.23"> expected but was
<"1.22999999999999998">
diff:
? 1.23               
?    2999999999999998
~~~

This seems to be some rounding issue.

**Comment by byroot** [comment]
Very interesting. Thanks for the heads up. 

I haven't noticed it myself, but indeed floats shouldn't be compared like this.

**Comment by byroot** [comment]
Feel free to PR an improvements, otherwise I might take a stab at it at a later date.

**Comment by byroot** [comment]
I think we fixed this a while ago.
