### ISSUE TITLE
disconnect change to disconnect! ?

### ISSUE THREAD

**Issue by sansroman** [redis/redis-rb#808]
```ruby
➜ rails console
Running via Spring preloader in process 79239
Loading development environment (Rails 5.2.1.1)
irb(main):001:0> redis = Redis.new
=> #<Redis client v4.0.3 for redis://127.0.0.1:6379/0>
irb(main):002:0> redis.quit
=> "OK"
irb(main):003:0>
Traceback (most recent call last):
	14: from -e:1:in `<main>'
	13: from /Users/tboevil/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	12: from /Users/tboevil/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	11: from /Users/tboevil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	10: from /Users/tboevil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	 9: from /Users/tboevil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	 8: from /Users/tboevil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	 7: from /Users/tboevil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `serve'
	 6: from /Users/tboevil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `fork'
	 5: from /Users/tboevil/work/spider/backend-rails/config/initializers/redis.rb:28:in `block in <main>'
	 4: from /Users/tboevil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/redis-4.0.3/lib/redis.rb:164:in `quit'
	 3: from /Users/tboevil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/redis-4.0.3/lib/redis.rb:50:in `synchronize'
	 2: from /Users/tboevil/.rbenv/versions/2.5.3/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	 1: from /Users/tboevil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/redis-4.0.3/lib/redis.rb:50:in `block in synchronize'
/Users/tboevil/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/redis-4.0.3/lib/redis.rb:169:in `block in quit': undefined method `disconnect' for #<Redis::SubscribedClient:0x00007fcc8d9e4f88> (NoMethodError)

```

It only have disconnect!, why ? Is there a problem with the config I wrote?

**Comment by byroot** [comment]
`undefined method `disconnect' for #<Redis::SubscribedClient:0x00007fcc8d9e4f88> (NoMethodError)`

This should be handled better in redis-rb, but this error says that this client is currently subscribed on a channel. That's a blocking operation. I don't know what use it in your app, but when you use this you should have a dedicated client for it because it makes the client unusable for other operations.

**Comment by sansroman** [comment]
thanks, websocket is using it, I think I understand
