### ISSUE TITLE
4.1.1 does not work with redis 3.2.x and <=4.0.10  sentinels setup with password-protected redis, 

### ISSUE THREAD

**Issue by misdoro** [redis/redis-rb#849]
Since update to 4.1.1, gem tries to send `auth` command to sentinels, if password is provided.

It does not work for redis 4 setup where only redis servers, but not sentinels, do support the auth command.

```
ERR unknown command 'auth'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:126:in `call'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:107:in `block in connect'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:306:in `with_reconnect'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:105:in `connect'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:381:in `ensure_connected'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:231:in `block in process'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:319:in `logging'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:230:in `process'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:125:in `call'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:607:in `block in resolve_master'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:584:in `block in sentinel_detect'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:576:in `each'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:576:in `sentinel_detect'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:606:in `resolve_master'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:565:in `resolve'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:344:in `establish_connection'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:106:in `block in connect'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:306:in `with_reconnect'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:105:in `connect'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:381:in `ensure_connected'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:231:in `block in process'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:319:in `logging'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:230:in `process'
...gems/2.6.0/gems/redis-4.1.1/lib/redis/client.rb:125:in `call'
...gems/2.6.0/gems/redis-4.1.1/lib/redis.rb:1447:in `block in smembers'
...gems/2.6.0/gems/redis-4.1.1/lib/redis.rb:52:in `block in synchronize'
...2.6.0/monitor.rb:230:in `mon_synchronize'
...gems/2.6.0/gems/redis-4.1.1/lib/redis.rb:52:in `synchronize'
...gems/2.6.0/gems/redis-4.1.1/lib/redis.rb:1446:in `smembers'
```

**Comment by misdoro** [comment]
I guess this can be closed: updating redis server and sentinel to 4.0.14 solved the issue.

**Comment by misdoro** [comment]
Well, 4.0.10 redis with sentinels is broken too for 4.1.1 :/

**Comment by byroot** [comment]
cc @supercaracal

**Comment by supercaracal** [comment]
I will look into and fix this. I am sorry.

**Comment by misdoro** [comment]
That might be caused by the quotes used in the rescue clause on line 600 of client.rb ```raise unless err.message.start_with?('ERR unknown command `auth`')```

**Comment by misdoro** [comment]
This can definitely be closed now: there is no good reason to stay with redis-rb 4.1.1 and newer versions don't have such issue.
