### ISSUE TITLE
OpenSSL issues in Fedora

### ISSUE THREAD

**Issue by pvalena** [redis/redis-rb#932]
When I run the test suite in Fedora, I get:

```
  1) Error:
SslTest#test_verified_ssl_connection:
OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/connection/ruby.rb:255:in `connect_nonblock'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/connection/ruby.rb:255:in `connect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/connection/ruby.rb:297:in `connect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:349:in `establish_connection'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:381:in `ensure_connected'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:233:in `block in process'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:320:in `logging'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:232:in `process'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:126:in `call'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis.rb:172:in `block in ping'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
    /usr/share/ruby/monitor.rb:202:in `synchronize'
    /usr/share/ruby/monitor.rb:202:in `mon_synchronize'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis.rb:171:in `ping'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/test/ssl_test.rb:19:in `block in test_verified_ssl_connection'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/test/support/redis_mock.rb:70:in `start_with_handler'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/test/support/redis_mock.rb:128:in `start'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/test/ssl_test.rb:17:in `test_verified_ssl_connection'

  2) Error:
SslTest#test_ssl_blocking:
OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/connection/ruby.rb:255:in `connect_nonblock'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/connection/ruby.rb:255:in `connect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/connection/ruby.rb:297:in `connect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:349:in `establish_connection'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:107:in `block in connect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:381:in `ensure_connected'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:233:in `block in process'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:320:in `logging'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:232:in `process'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis/client.rb:126:in `call'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis.rb:848:in `block in set'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'
    /usr/share/ruby/monitor.rb:202:in `synchronize'
    /usr/share/ruby/monitor.rb:202:in `mon_synchronize'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/lib/redis.rb:844:in `set'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/test/ssl_test.rb:44:in `block in test_ssl_blocking'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/test/support/redis_mock.rb:70:in `start_with_handler'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/test/support/redis_mock.rb:128:in `start'
    /builddir/build/BUILD/redis-4.2.1/usr/share/gems/gems/redis-4.2.1/test/ssl_test.rb:42:in `test_ssl_blocking'

```

Test suite is executed during build like so:
```
$ export DRIVER=ruby
$ make TIMEOUT=15 BINARY=/usr/bin/redis-server REDIS_CLIENT=/usr/bin/redis-cli 'BUILD_DIR=${TMP}'
```

This was previously fine, the OpenSSL, but ciphers are probably stricter now.

**Comment by pvalena** [comment]
Any news on this?
