### ISSUE TITLE
Redis#exists and Redis#exists? both raising `NoMethodError: undefined method '>' for false:FalseClass`

### ISSUE THREAD

**Issue by marksiemers** [redis/redis-rb#946]
With `exists_returns_integer` set to true, `#exists` works but `exists?` does not:
```
> Redis.exists_returns_integer = true
=> true
> Redis.new.exists('hello')
=> false
> Redis.new.exists?('hello')
NoMethodError: undefined method `>' for false:FalseClass
from /Users/mark/github/AbleHealth/able/bundle/ruby/2.6.0/gems/redis-4.2.2/lib/redis.rb:606:in `block (2 levels) in exists?'
```

With `exists_returns_integer` set to false, they both do not work:
```
> Redis.exists_returns_integer = false
`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.
=> false
> Redis.new.exists('hello')
NoMethodError: undefined method `>' for false:FalseClass
from /Users/mark/github/AbleHealth/able/bundle/ruby/2.6.0/gems/redis-4.2.2/lib/redis.rb:606:in `block (2 levels) in exists?'
> Redis.new.exists?('hello')
NoMethodError: undefined method `>' for false:FalseClass
from /Users/mark/github/AbleHealth/able/bundle/ruby/2.6.0/gems/redis-4.2.2/lib/redis.rb:606:in `block (2 levels) in exists?'
```

The method looks like this:
```ruby
  # Determine if any of the keys exists.
  #
  # @param [String, Array<String>] keys
  # @return [Boolean]
  def exists?(*keys)
    synchronize do |client|
      client.call([:exists, *keys]) do |value|
        value > 0
      end
    end
  end
```
And value ends up being `false`

Please let me know if any additional information is needed.

Thank you.

**Comment by marksiemers** [comment]
Sorry about this - it wasn't obvious to me, but I think this is coming from a `fakeredis` gem. I didn't see that gem in the backtrace with the error, but I ran rails in development instead of test and the errors above went away.
